## Supabase connect get data

In [59]:
import os
from dotenv import load_dotenv
from supabase import create_client
import pandas as pd
from datetime import datetime, timedelta, date
import pandas as pd
import holidays

import numpy as np


# Load env
load_dotenv()

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")

supabase = create_client(SUPABASE_URL, SUPABASE_KEY)
print(SUPABASE_URL)

response = supabase.rpc("delete_outlier_data_by_year", {"tahun_param": 2026}).execute()
print(response.data)

https://extlxiwpcbzqaalpopqn.supabase.co

03/03/2026 01:55:53 PM - HTTP Request: POST https://extlxiwpcbzqaalpopqn.supabase.co/rest/v1/rpc/delete_outlier_data_by_year "HTTP/2 204 No Content"

[]

In [60]:
# Fungsi untuk mengambil data dengan paginasi dan filter tahun
def fetch_data_with_pagination_and_year(table_name, year, limit=1000):
    offset = 0
    all_data = []
    
    while True:
        # Ambil data per halaman (limit) dengan filter tahun menggunakan format tanggal
        response = supabase.table(table_name).select("*").filter("tanggal", "gte", f"{year}-01-01").filter("tanggal", "lt", f"{year + 1}-01-01").range(offset, offset + limit - 1).execute()
        
        # Cek apakah ada data yang diterima
        if len(response.data) == 0:
            break
        
        # Gabungkan data yang sudah diambil
        all_data.extend(response.data)
        
        # Update offset untuk mengambil data berikutnya
        offset += limit
    
    return all_data

# Ambil data dari tabel harga_beras untuk tahun 2025
data_harga_beras = fetch_data_with_pagination_and_year("harga_beras", 2026)
data_harga_beras = pd.DataFrame(data_harga_beras)

# Tampilkan jumlah data yang diambil
print(f"Jumlah data untuk tahun 2026 yang diambil: {len(data_harga_beras)}")
data_harga_beras

03/03/2026 01:55:53 PM - HTTP Request: GET https://extlxiwpcbzqaalpopqn.supabase.co/rest/v1/harga_beras?select=%2A&tanggal=gte.2026-01-01&tanggal=lt.2027-01-01&offset=0&limit=1000 "HTTP/2 200 OK"
03/03/2026 01:55:53 PM - HTTP Request: GET https://extlxiwpcbzqaalpopqn.supabase.co/rest/v1/harga_beras?select=%2A&tanggal=gte.2026-01-01&tanggal=lt.2027-01-01&offset=1000&limit=1000 "HTTP/2 200 OK"
03/03/2026 01:55:53 PM - HTTP Request: GET https://extlxiwpcbzqaalpopqn.supabase.co/rest/v1/harga_beras?select=%2A&tanggal=gte.2026-01-01&tanggal=lt.2027-01-01&offset=2000&limit=1000 "HTTP/2 200 OK"
03/03/2026 01:55:54 PM - HTTP Request: GET https://extlxiwpcbzqaalpopqn.supabase.co/rest/v1/harga_beras?select=%2A&tanggal=gte.2026-01-01&tanggal=lt.2027-01-01&offset=3000&limit=1000 "HTTP/2 200 OK"
03/03/2026 01:55:54 PM - HTTP Request: GET https://extlxiwpcbzqaalpopqn.supabase.co/rest/v1/harga_beras?select=%2A&tanggal=gte.2026-01-01&tanggal=lt.2027-01-01&offset=4000&limit=1000 "HTTP/2 200 OK"
03/03/2026 01:55:54 PM - HTTP Request: GET https://extlxiwpcbzqaalpopqn.supabase.co/rest/v1/harga_beras?select=%2A&tanggal=gte.2026-01-01&tanggal=lt.2027-01-01&offset=5000&limit=1000 "HTTP/2 200 OK"
03/03/2026 01:55:54 PM - HTTP Request: GET https://extlxiwpcbzqaalpopqn.supabase.co/rest/v1/harga_beras?select=%2A&tanggal=gte.2026-01-01&tanggal=lt.2027-01-01&offset=6000&limit=1000 "HTTP/2 200 OK"
03/03/2026 01:55:54 PM - HTTP Request: GET https://extlxiwpcbzqaalpopqn.supabase.co/rest/v1/harga_beras?select=%2A&tanggal=gte.2026-01-01&tanggal=lt.2027-01-01&offset=7000&limit=1000 "HTTP/2 200 OK"
03/03/2026 01:55:55 PM - HTTP Request: GET https://extlxiwpcbzqaalpopqn.supabase.co/rest/v1/harga_beras?select=%2A&tanggal=gte.2026-01-01&tanggal=lt.2027-01-01&offset=8000&limit=1000 "HTTP/2 200 OK"
03/03/2026 01:55:55 PM - HTTP Request: GET https://extlxiwpcbzqaalpopqn.supabase.co/rest/v1/harga_beras?select=%2A&tanggal=gte.2026-01-01&tanggal=lt.2027-01-01&offset=9000&limit=1000 "HTTP/2 200 OK"

Jumlah data untuk tahun 2026 yang diambil: 8621

          id  kode_kab_kota     tanggal  variant_id    harga  tipe_harga_id
0     122461           3501  2026-01-02           1  12300.0              2
1     122462           3503  2026-01-02           1  13000.0              2
2     122463           3504  2026-01-02           1  12650.0              2
3     122464           3505  2026-01-02           1  12750.0              2
4     122465           3506  2026-01-02           1  12500.0              2
...      ...            ...         ...         ...      ...            ...
8616  245646           3578  2026-02-26           2  15500.0              1
8617  245647           3579  2026-02-26           1  12800.0              1
8618  245648           3579  2026-02-26           2  14750.0              1
8619  245649              1  2026-02-26           1  12883.0              1
8620  245650              1  2026-02-26           2  14664.0              1

[8621 rows x 6 columns]

In [61]:
last_id_group = supabase.rpc("last_outlier_ids").execute().data[0]["last_group_id"]
last_id_detail = supabase.rpc("last_outlier_ids").execute().data[0]["last_detail_id"]

print(f"Last id group {last_id_group} \n last id detail {last_id_detail}")

03/03/2026 01:55:55 PM - HTTP Request: POST https://extlxiwpcbzqaalpopqn.supabase.co/rest/v1/rpc/last_outlier_ids "HTTP/2 200 OK"
03/03/2026 01:55:55 PM - HTTP Request: POST https://extlxiwpcbzqaalpopqn.supabase.co/rest/v1/rpc/last_outlier_ids "HTTP/2 200 OK"

Last id group 539
 last id detail 13181

## detect outlier

In [62]:
def detect_iqr_outlier(df):
    df = df.copy()
    df["is_outlier"] = False

    group_cols = ["tahun", "variant_id", "tipe_harga_id", "kode_kab_kota"]

    for keys, g in df.groupby(group_cols):
        print("group is = ", group_cols)
        print("Group:", keys)
        print("Jumlah data:", len(g))

        q1 = g["harga"].quantile(0.25)
        q3 = g["harga"].quantile(0.75)
        iqr = q3 - q1

        print("Q1:", q1, "Q3:", q3, "IQR:", iqr)

        lower = q1 - 1.5 * iqr
        upper = q3 + 1.5 * iqr

        print("Lower:", lower, "Upper:", upper)
        print("-"*40)

        idx = g[(g["harga"] < lower) | (g["harga"] > upper)].index
        df.loc[idx, "is_outlier"] = True

    return df



data_harga_beras["tanggal"] = pd.to_datetime(data_harga_beras["tanggal"])
data_harga_beras["tahun"] = data_harga_beras["tanggal"].dt.year
data_harga_beras = detect_iqr_outlier(data_harga_beras)

# ===============================
# INISIALISASI HOLIDAYS INDONESIA
# ===============================
id_holidays = holidays.Indonesia(years=range(data_harga_beras["tahun"].min(), data_harga_beras["tahun"].max() + 1))

group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(1))
Jumlah data: 36
Q1: 12824.25 Q3: 12831.0 IQR: 6.75
Lower: 12814.125 Upper: 12841.125
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3501))
Jumlah data: 36
Q1: 12824.25 Q3: 12831.0 IQR: 6.75
Lower: 12814.125 Upper: 12841.125
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3502))
Jumlah data: 36
Q1: 12809.0 Q3: 12831.0 IQR: 22.0
Lower: 12776.0 Upper: 12864.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3503))
Jumlah data: 36
Q1: 12809.0 Q3: 12831.0 IQR: 22.0
Lower: 12776.0 Upper: 12864.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3504))
Jumlah data: 36
Q1: 12824.25 Q3: 12831.0 IQR: 6.75
Lower: 12814.125 Upper: 12841.125
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3505))
Jumlah data: 36
Q1: 12824.25 Q3: 12831.0 IQR: 6.75
Lower: 12814.125 Upper: 12841.125
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3506))
Jumlah data: 36
Q1: 12809.0 Q3: 12831.0 IQR: 22.0
Lower: 12776.0 Upper: 12864.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3507))
Jumlah data: 36
Q1: 12824.25 Q3: 12831.0 IQR: 6.75
Lower: 12814.125 Upper: 12841.125
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3508))
Jumlah data: 36
Q1: 12809.0 Q3: 12831.0 IQR: 22.0
Lower: 12776.0 Upper: 12864.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3509))
Jumlah data: 36
Q1: 12824.25 Q3: 12831.0 IQR: 6.75
Lower: 12814.125 Upper: 12841.125
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3510))
Jumlah data: 36
Q1: 12824.25 Q3: 12831.0 IQR: 6.75
Lower: 12814.125 Upper: 12841.125
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3511))
Jumlah data: 36
Q1: 12824.25 Q3: 12831.0 IQR: 6.75
Lower: 12814.125 Upper: 12841.125
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3512))
Jumlah data: 36
Q1: 12809.0 Q3: 12831.0 IQR: 22.0
Lower: 12776.0 Upper: 12864.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3513))
Jumlah data: 36
Q1: 12809.0 Q3: 12831.0 IQR: 22.0
Lower: 12776.0 Upper: 12864.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3514))
Jumlah data: 36
Q1: 12824.25 Q3: 12831.0 IQR: 6.75
Lower: 12814.125 Upper: 12841.125
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3515))
Jumlah data: 36
Q1: 12824.25 Q3: 12831.0 IQR: 6.75
Lower: 12814.125 Upper: 12841.125
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3516))
Jumlah data: 36
Q1: 12809.0 Q3: 12831.0 IQR: 22.0
Lower: 12776.0 Upper: 12864.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3517))
Jumlah data: 36
Q1: 12809.0 Q3: 12831.0 IQR: 22.0
Lower: 12776.0 Upper: 12864.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3518))
Jumlah data: 36
Q1: 12824.25 Q3: 12831.0 IQR: 6.75
Lower: 12814.125 Upper: 12841.125
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3519))
Jumlah data: 36
Q1: 12809.0 Q3: 12831.0 IQR: 22.0
Lower: 12776.0 Upper: 12864.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3520))
Jumlah data: 36
Q1: 12824.25 Q3: 12831.0 IQR: 6.75
Lower: 12814.125 Upper: 12841.125
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3521))
Jumlah data: 36
Q1: 12824.25 Q3: 12831.0 IQR: 6.75
Lower: 12814.125 Upper: 12841.125
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3522))
Jumlah data: 36
Q1: 12809.0 Q3: 12831.0 IQR: 22.0
Lower: 12776.0 Upper: 12864.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3523))
Jumlah data: 36
Q1: 12810.0 Q3: 12831.0 IQR: 21.0
Lower: 12778.5 Upper: 12862.5
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3524))
Jumlah data: 36
Q1: 12824.25 Q3: 12831.0 IQR: 6.75
Lower: 12814.125 Upper: 12841.125
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3525))
Jumlah data: 31
Q1: 12817.5 Q3: 12831.0 IQR: 13.5
Lower: 12797.25 Upper: 12851.25
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3526))
Jumlah data: 36
Q1: 12809.0 Q3: 12831.0 IQR: 22.0
Lower: 12776.0 Upper: 12864.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3527))
Jumlah data: 36
Q1: 12824.25 Q3: 12831.0 IQR: 6.75
Lower: 12814.125 Upper: 12841.125
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3528))
Jumlah data: 36
Q1: 12809.0 Q3: 12831.0 IQR: 22.0
Lower: 12776.0 Upper: 12864.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3529))
Jumlah data: 36
Q1: 12824.25 Q3: 12831.0 IQR: 6.75
Lower: 12814.125 Upper: 12841.125
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3571))
Jumlah data: 36
Q1: 12824.25 Q3: 12831.0 IQR: 6.75
Lower: 12814.125 Upper: 12841.125
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3572))
Jumlah data: 36
Q1: 12824.25 Q3: 12831.0 IQR: 6.75
Lower: 12814.125 Upper: 12841.125
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3573))
Jumlah data: 36
Q1: 12824.25 Q3: 12831.0 IQR: 6.75
Lower: 12814.125 Upper: 12841.125
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3574))
Jumlah data: 36
Q1: 12809.0 Q3: 12831.0 IQR: 22.0
Lower: 12776.0 Upper: 12864.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3575))
Jumlah data: 36
Q1: 12824.25 Q3: 12831.0 IQR: 6.75
Lower: 12814.125 Upper: 12841.125
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3576))
Jumlah data: 36
Q1: 12824.25 Q3: 12831.0 IQR: 6.75
Lower: 12814.125 Upper: 12841.125
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3577))
Jumlah data: 36
Q1: 12824.25 Q3: 12831.0 IQR: 6.75
Lower: 12814.125 Upper: 12841.125
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3578))
Jumlah data: 31
Q1: 12817.5 Q3: 12831.0 IQR: 13.5
Lower: 12797.25 Upper: 12851.25
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(1), np.int64(3579))
Jumlah data: 36
Q1: 12809.0 Q3: 12831.0 IQR: 22.0
Lower: 12776.0 Upper: 12864.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(1))
Jumlah data: 56
Q1: 12583.0 Q3: 12719.0 IQR: 136.0
Lower: 12379.0 Upper: 12923.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3501))
Jumlah data: 51
Q1: 12467.0 Q3: 12500.0 IQR: 33.0
Lower: 12417.5 Upper: 12549.5
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3502))
Jumlah data: 6
Q1: 11950.0 Q3: 12033.25 IQR: 83.25
Lower: 11825.125 Upper: 12158.125
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3503))
Jumlah data: 55
Q1: 13000.0 Q3: 13000.0 IQR: 0.0
Lower: 13000.0 Upper: 13000.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3504))
Jumlah data: 56
Q1: 12790.0 Q3: 12790.0 IQR: 0.0
Lower: 12790.0 Upper: 12790.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3505))
Jumlah data: 56
Q1: 12400.25 Q3: 12754.25 IQR: 354.0
Lower: 11869.25 Upper: 13285.25
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3506))
Jumlah data: 8
Q1: 12500.0 Q3: 12500.0 IQR: 0.0
Lower: 12500.0 Upper: 12500.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3507))
Jumlah data: 38
Q1: 12831.25 Q3: 13275.0 IQR: 443.75
Lower: 12165.625 Upper: 13940.625
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3508))
Jumlah data: 41
Q1: 12400.0 Q3: 12450.0 IQR: 50.0
Lower: 12325.0 Upper: 12525.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3509))
Jumlah data: 6
Q1: 12500.0 Q3: 12500.0 IQR: 0.0
Lower: 12500.0 Upper: 12500.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3510))
Jumlah data: 56
Q1: 12628.75 Q3: 12970.0 IQR: 341.25
Lower: 12116.875 Upper: 13481.875
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3511))
Jumlah data: 47
Q1: 11600.0 Q3: 12500.0 IQR: 900.0
Lower: 10250.0 Upper: 13850.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3512))
Jumlah data: 26
Q1: 12750.0 Q3: 12800.0 IQR: 50.0
Lower: 12675.0 Upper: 12875.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3513))
Jumlah data: 44
Q1: 12650.0 Q3: 12850.0 IQR: 200.0
Lower: 12350.0 Upper: 13150.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3514))
Jumlah data: 51
Q1: 12500.0 Q3: 12500.0 IQR: 0.0
Lower: 12500.0 Upper: 12500.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3515))
Jumlah data: 47
Q1: 12500.0 Q3: 12750.0 IQR: 250.0
Lower: 12125.0 Upper: 13125.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3516))
Jumlah data: 44
Q1: 12550.0 Q3: 12831.25 IQR: 281.25
Lower: 12128.125 Upper: 13253.125
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3517))
Jumlah data: 21
Q1: 13000.0 Q3: 13000.0 IQR: 0.0
Lower: 13000.0 Upper: 13000.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3518))
Jumlah data: 53
Q1: 12500.0 Q3: 13000.0 IQR: 500.0
Lower: 11750.0 Upper: 13750.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3519))
Jumlah data: 56
Q1: 12528.0 Q3: 12709.0 IQR: 181.0
Lower: 12256.5 Upper: 12980.5
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3520))
Jumlah data: 53
Q1: 12575.0 Q3: 12600.0 IQR: 25.0
Lower: 12537.5 Upper: 12637.5
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3521))
Jumlah data: 56
Q1: 13000.0 Q3: 13000.0 IQR: 0.0
Lower: 13000.0 Upper: 13000.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3522))
Jumlah data: 47
Q1: 12000.0 Q3: 12612.5 IQR: 612.5
Lower: 11081.25 Upper: 13531.25
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3523))
Jumlah data: 54
Q1: 12000.0 Q3: 12000.0 IQR: 0.0
Lower: 12000.0 Upper: 12000.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3524))
Jumlah data: 56
Q1: 12770.0 Q3: 12770.0 IQR: 0.0
Lower: 12770.0 Upper: 12770.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3525))
Jumlah data: 55
Q1: 12625.0 Q3: 12847.5 IQR: 222.5
Lower: 12291.25 Upper: 13181.25
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3526))
Jumlah data: 53
Q1: 12500.0 Q3: 12500.0 IQR: 0.0
Lower: 12500.0 Upper: 12500.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3527))
Jumlah data: 44
Q1: 11500.0 Q3: 12000.0 IQR: 500.0
Lower: 10750.0 Upper: 12750.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3528))
Jumlah data: 52
Q1: 12250.0 Q3: 12350.0 IQR: 100.0
Lower: 12100.0 Upper: 12500.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3529))
Jumlah data: 56
Q1: 12617.0 Q3: 12925.0 IQR: 308.0
Lower: 12155.0 Upper: 13387.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3571))
Jumlah data: 56
Q1: 12807.5 Q3: 12883.0 IQR: 75.5
Lower: 12694.25 Upper: 12996.25
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3572))
Jumlah data: 50
Q1: 13072.25 Q3: 13425.0 IQR: 352.75
Lower: 12543.125 Upper: 13954.125
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3573))
Jumlah data: 47
Q1: 12000.0 Q3: 12500.0 IQR: 500.0
Lower: 11250.0 Upper: 13250.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3574))
Jumlah data: 53
Q1: 12550.0 Q3: 12650.0 IQR: 100.0
Lower: 12400.0 Upper: 12800.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3575))
Jumlah data: 47
Q1: 12550.0 Q3: 13500.0 IQR: 950.0
Lower: 11125.0 Upper: 14925.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3576))
Jumlah data: 50
Q1: 13270.75 Q3: 13500.0 IQR: 229.25
Lower: 12926.875 Upper: 13843.875
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3577))
Jumlah data: 56
Q1: 12750.0 Q3: 12800.0 IQR: 50.0
Lower: 12675.0 Upper: 12875.0
----------------------------------------
group is =  ['tahun', 'variant_id', 'tipe_harga_id', 'kode_kab_kota']
Group: (np.int32(2026), np.int64(1), np.int64(2), np.int64(3578))
Jumlah data: 56
Q1: 12775.0 Q3: 12854.75 IQR: 79.75
Lower: 12655.375 Upper: 12974.375
----------------------------------------

## Grouping Outlier

In [63]:
def cluster_outlier(df, max_hari=14):
    """
    Membentuk cluster outlier berdasarkan tanggal berurutan
    dan maksimal durasi cluster = max_hari
    
    Cluster dibuat per kombinasi:
    tahun, variant_id, tipe_harga_id
    """

    df = df.copy()
    df["tanggal"] = pd.to_datetime(df["tanggal"])
    df["tahun"] = df["tanggal"].dt.year

    # ==============================
    # FILTER OUTLIER
    # ==============================
    out = df[df["is_outlier"] == True].copy()

    if out.empty:
        df["cluster_id"] = pd.NA
        return pd.DataFrame(), df

    out = out.sort_values(
        ["tahun", "variant_id", "tipe_harga_id", "tanggal"]
    )

    # ==============================
    # BENTUK CLUSTER DENGAN LOOP
    # ==============================
    cluster_list = []

    for keys, group in out.groupby(
        ["tahun", "variant_id", "tipe_harga_id"]
    ):
        group = group.sort_values("tanggal").copy()

        cluster_local = 1
        start_date = group.iloc[0]["tanggal"]
        prev_date = start_date

        clusters = [cluster_local]

        for i in range(1, len(group)):
            current_date = group.iloc[i]["tanggal"]

            selisih = (current_date - prev_date).days
            durasi = (current_date - start_date).days + 1

            # Putus cluster jika:
            # 1. Tidak berurutan (>1 hari)
            # 2. Durasi sudah melebihi max_hari
            if selisih > 1 or durasi > max_hari:
                cluster_local += 1
                start_date = current_date

            clusters.append(cluster_local)
            prev_date = current_date

        group["cluster_local"] = clusters
        cluster_list.append(group)

    out = pd.concat(cluster_list)

    # ==============================
    # SUMMARY CLUSTER
    # ==============================
    df_out = (
        out.groupby(
            ["tahun", "variant_id", "tipe_harga_id", "cluster_local"]
        )
        .agg(
            start_date=("tanggal", "min"),
            end_date=("tanggal", "max"),
            jumlah_data=("tanggal", "count")
        )
        .reset_index()
    )

    df_out["durasi_hari"] = (
        df_out["end_date"] - df_out["start_date"]
    ).dt.days + 1

    # ==============================
    # GLOBAL CLUSTER ID
    # ==============================
    df_out = df_out.sort_values(
        ["tahun", "variant_id", "tipe_harga_id", "start_date"]
    ).reset_index(drop=True)

    df_out["cluster_id"] = df_out.index + 1

    # ==============================
    # MAP KE OUTLIER
    # ==============================
    out = out.merge(
        df_out[
            ["tahun", "variant_id", "tipe_harga_id",
             "cluster_local", "cluster_id"]
        ],
        on=["tahun", "variant_id", "tipe_harga_id", "cluster_local"],
        how="left"
    )

    # ==============================
    # MERGE KE FULL DATA
    # ==============================
    df_full = df.merge(
        out[
            ["kode_kab_kota", "tanggal",
             "variant_id", "tipe_harga_id", "cluster_id"]
        ],
        on=["kode_kab_kota", "tanggal",
            "variant_id", "tipe_harga_id"],
        how="left"
    )

    df_full["cluster_id"] = df_full["cluster_id"].astype("Int64")

    return df_out, df_full

df_out, df_full = cluster_outlier(data_harga_beras)

In [64]:
df_out

,tahun,variant_id,tipe_harga_id,cluster_local,start_date,end_date,jumlah_data,durasi_hari,cluster_id
0,2026,1,1,1,2026-02-02,2026-02-06,110,5,1
1,2026,1,1,2,2026-02-09,2026-02-10,44,2,2
2,2026,1,1,3,2026-02-20,2026-02-20,36,1,3
3,2026,1,1,4,2026-02-23,2026-02-26,144,4,4
4,2026,1,2,1,2026-01-02,2026-01-15,136,14,5
5,2026,1,2,2,2026-01-16,2026-01-27,45,12,6
6,2026,1,2,3,2026-01-30,2026-01-30,2,1,7
7,2026,1,2,4,2026-02-02,2026-02-09,10,8,8
8,2026,1,2,5,2026-02-15,2026-02-17,5,3,9
9,2026,1,2,6,2026-02-19,2026-02-19,1,1,10
10,2026,1,2,7,2026-02-21,2026-02-26,7,6,11
11,2026,1,3,1,2026-01-02,2026-01-09,24,8,12
12,2026,1,3,2,2026-01-11,2026-01-24,29,14,13
13,2026,1,3,3,2026-01-25,2026-01-26,6,2,14
14,2026,1,3,4,2026-02-01,2026-02-03,5,3,15
15,2026,1,3,5,2026-02-05,2026-02-09,5,5,16
16,2026,1,3,6,2026-02-11,2026-02-12,3,2,17
17,2026,1,3,7,2026-02-15,2026-02-15,1,1,18
18,2026,1,3,8,2026-02-17,2026-02-26,22,10,19
19,2026,2,1,1,2026-01-07,2026-01-09,78,3,20
20,2026,2,1,2,2026-01-12,2026-01-14,78,3,21
21,2026,2,1,3,2026-02-05,2026-02-05,27,1,22
22,2026,2,1,4,2026-02-10,2026-02-10,26,1,23
23,2026,2,1,5,2026-02-12,2026-02-13,66,2,24
24,2026,2,1,6,2026-02-18,2026-02-18,39,1,25
25,2026,2,1,7,2026-02-20,2026-02-20,38,1,26
26,2026,2,1,8,2026-02-23,2026-02-26,152,4,27
27,2026,2,2,1,2026-01-02,2026-01-14,52,13,28
28,2026,2,2,2,2026-01-17,2026-01-27,19,11,29
29,2026,2,2,3,2026-01-29,2026-02-03,6,6,30
30,2026,2,2,4,2026-02-05,2026-02-06,3,2,31
31,2026,2,2,5,2026-02-09,2026-02-14,14,6,32
32,2026,2,2,6,2026-02-16,2026-02-26,46,11,33
33,2026,2,3,1,2026-01-02,2026-01-08,11,7,34
34,2026,2,3,2,2026-01-12,2026-01-12,1,1,35
35,2026,2,3,3,2026-01-14,2026-01-14,1,1,36
36,2026,2,3,4,2026-01-23,2026-01-25,5,3,37
37,2026,2,3,5,2026-01-27,2026-01-27,2,1,38
38,2026,2,3,6,2026-01-29,2026-01-30,2,2,39
39,2026,2,3,7,2026-02-02,2026-02-02,3,1,40
40,2026,2,3,8,2026-02-04,2026-02-04,1,1,41
41,2026,2,3,9,2026-02-06,2026-02-06,1,1,42
42,2026,2,3,10,2026-02-14,2026-02-14,1,1,43
43,2026,2,3,11,2026-02-16,2026-02-26,15,11,44

In [65]:
df_full.groupby('is_outlier').size()

is_outlier
False    7299
True     1322
dtype: int64

## Give information outlier

In [66]:
from gnews import GNews
import urllib.parse

def get_gnews_by_date(start_date, end_date,
                      language='id', country='ID'):
    
    keyword_raw = "harga OR impor beras OR logistik OR pangan OR cuaca ekstrim jawa timur"
    keyword = urllib.parse.quote(keyword_raw)
    # ✅ Pastikan format tuple
    if not isinstance(start_date, tuple):
        start_date = (start_date.year, start_date.month, start_date.day)

    if not isinstance(end_date, tuple):
        end_date = (end_date.year, end_date.month, end_date.day)
    
    google_news = GNews(
        language=language,
        country=country
    )
    
    google_news.start_date = start_date
    google_news.end_date = end_date
    
    news = google_news.get_news(keyword)
    
    # print("DEBUG jumlah raw news:", len(news))  # tambahkan debug
    
    data = []
    for article in news:
        data.append({
            "tanggal": article.get('published date'),
            "judul": article.get('title'),
            "sumber": article.get('publisher', {}).get('title'),
            "url": article.get('url')
        })
    
    df_news = pd.DataFrame(data)

    kalimat = df_to_sentences(df_news)
    
    # print("Jumlah berita: \n", kalimat)
    
    return kalimat

def df_to_sentences(df):
    sentences = []
    
    for _, row in df.iterrows():
        kalimat = (
            f"Pada {row['tanggal']}, media {row['sumber']} "
            f"memberitakan: \"{row['judul']}\"."
        )
        sentences.append(kalimat)
    
    return sentences

# ===============================
# FUNGSI UNTUK DETEKSI HARI LIBUR DI RENTANG
# ===============================
def get_holidays_in_range(start_date, end_date, buffer_days=7):
    """
    Deteksi hari libur dalam rentang tanggal, plus buffer sebelum/sesudah
    """
    holiday_list = []
    
    # Extend range dengan buffer
    extended_start = start_date - timedelta(days=buffer_days)
    extended_end = end_date + timedelta(days=buffer_days)
    
    current = extended_start
    while current <= extended_end:
        if current in id_holidays:
            holiday_list.append({
                'date': current,
                'name': id_holidays[current]
            })
        current += timedelta(days=1)
    
    return holiday_list



import re
from datetime import datetime

def format_news_item(news_text):
    """
    Parsing string berita menjadi format:
    - Menurut media X, pada Tanggal, Judul
    """

    # Contoh format:
    # Pada Sat, 10 Apr 2021 07:00:00 GMT, media Ngopibareng.id memberitakan: "Judul - Ngopibareng.id"

    pattern = r"Pada .*?, (\d{2} \w{3} \d{4}).*?media (.*?) memberitakan: \"(.*?)\""
    match = re.search(pattern, news_text)

    if match:
        tanggal = match.group(1)
        media = match.group(2)
        judul = match.group(3).split(" - ")[0]  # buang suffix nama media

        return f"- Menurut media {media}, pada {tanggal}, {judul}"
    
    return None


def ask_event_indonesia(start_date, end_date):

    holidays_found = get_holidays_in_range(start_date, end_date, buffer_days=7)
    berita = get_gnews_by_date(start_date, end_date)
    # print(berita)
    output_lines = []

    # ===============================
    # HOLIDAY SECTION
    # ===============================
    if holidays_found:
        output_lines.append("Berdekatan dengan hari besar:")

        for h in holidays_found:
            tanggal = h['date'].strftime('%d-%m-%Y')
            nama = h['name']
            output_lines.append(f"- {nama} ({tanggal})")


    # ===============================
    # NEWS SECTION
    # ===============================
    formatted_news = []


    for item in berita:
        formatted = format_news_item(item)
        if formatted:
            formatted_news.append(formatted)

    if formatted_news:
        if output_lines:
            output_lines.append("")  # spasi antar section
        output_lines.append("Terjadi peristiwa:")
        output_lines.extend(formatted_news)

    



    print(f"total berita {len(formatted_news)} | holiday {len(output_lines)}")
    print(f"hari besar \n {output_lines}")
    print(f"news \n {formatted_news}")

    # ===============================
    # FALLBACK
    # ===============================
    if not output_lines:
        return "Tidak ditemukan peristiwa dalam periode tersebut."

    return "\n".join(output_lines)

In [67]:
import time

def analyze_df_events(df_group, df_detail, sample_n=None, delay=2, error_delay=5):
    """
    Tambahkan kolom 'deskripsi' berdasarkan start_date & end_date.

    Parameters:
        df_group   : dataframe cluster (start_date, end_date, cluster_id)
        df_detail  : dataframe detail (is_outlier, id, cluster_id)
        sample_n   : jumlah baris diproses (None = semua)
        delay      : jeda normal antar request (detik)
        error_delay: jeda jika error (detik)
    """

    if sample_n == 999:
        sample_n = len(df_detail[df_detail["is_outlier"] == True])

    df = df_group.copy()

    df['start_date'] = pd.to_datetime(df['start_date'])
    df['end_date']   = pd.to_datetime(df['end_date'])

    target_df = df.head(sample_n) if sample_n else df

    total = len(target_df)

    print(f"\nTotal yang diproses: {total} baris\n")

    for i, (idx, row) in enumerate(target_df.iterrows(), 1):

        print(f" id {idx} [{i}/{total}] {row['start_date'].date()} → {row['end_date'].date()} ...", end=" ")

        try:
            analisis = ask_event_indonesia(row['start_date'], row['end_date'])
            df.loc[idx, 'deskripsi'] = analisis
            # print("✅")

            # delay normal
            if i < total:
                time.sleep(delay)

        except Exception as e:
            df.loc[idx, 'deskripsi'] = f"ERROR: {e}"
            print(f"❌ {e}")

            # delay lebih lama jika error
            time.sleep(error_delay)

    # ===============================
    # PREPARE OUTPUT
    # ===============================

    # ===============================
    # OUTLIER DETAIL
    # ===============================
    df_outlier_detail = (
        df_detail[df_detail["is_outlier"] == True][['id', 'cluster_id']]
        .reset_index(drop=True)
    )

    df_outlier_detail.insert(0, 'row_id', range(1, len(df_outlier_detail) + 1))


    # ===============================
    # OUTLIER GROUP
    # ===============================
    df_outlier_group = (
        df[['cluster_id', 'deskripsi']]
        .reset_index(drop=True)
    )

    df_outlier_group.insert(0, 'row_id', range(1, len(df_outlier_group) + 1))

    df_outlier_detail = df_outlier_detail.reset_index(drop=True)
    df_outlier_group  = df_outlier_group.reset_index(drop=True)

    return df_outlier_detail, df_outlier_group


# # ===============================
# # CONTOH PENGGUNAAN
# # ===============================

# # Test 3 baris dulu sebelum proses semua
# outlier_detail, outlier_group = analyze_df_events(df_out, df_full, sample_n=1)
# # print(outlier_group.iloc[0]['deskripsi'])

In [68]:
def analyze_in_batches(df_group, df_detail, batch_size=50, delay_between_batch=10):
    
    total = len(df_group)
    results_detail = []
    results_group = []
    
    print(f"Total cluster: {total}")
    print(f"Batch size: {batch_size}")
    print(f"Total batch: {(total // batch_size) + 1}\n")
    
    for start in range(0, total, batch_size):
        
        end = start + batch_size
        print(f"\n===== PROSES BATCH {start} - {min(end, total)} =====")
        
        df_batch = df_group.iloc[start:end]
        
        detail, group = analyze_df_events(
            df_batch,
            df_detail,
            sample_n=None,
            delay=2,
            error_delay=5
        )
        
        results_detail.append(detail)
        results_group.append(group)
        
        # Delay antar batch supaya API aman
        if end < total:
            print(f"\n⏳ Tunggu {delay_between_batch} detik sebelum batch berikutnya...\n")
            time.sleep(delay_between_batch)
    
    final_detail = pd.concat(results_detail, ignore_index=True)
    final_group  = pd.concat(results_group, ignore_index=True)
    
    return final_detail, final_group

outlier_detail, outlier_group = analyze_in_batches(
    df_out,
    df_full,
    batch_size=50,
    delay_between_batch=15
)

Total cluster: 44
Batch size: 50
Total batch: 1


===== PROSES BATCH 0 - 44 =====

Total yang diproses: 44 baris

 id 0 [1/44] 2026-02-02 → 2026-02-06 ... total berita 6 | holiday 7
hari besar
 ['Terjadi peristiwa:', '- Menurut media CNN Indonesia, pada 06 Feb 2026, Peringatan BMKG: Cuaca Ekstrem Mengintai Indonesia Sepekan ke Depan', '- Menurut media CNN Indonesia, pada 06 Feb 2026, Dampak Krisis Iklim, Hujan di Indonesia Makin Ekstrem', '- Menurut media ANTARA News Megapolitan, pada 02 Feb 2026, 19 rumah warga rusak akibat hujan dan angin kencang di Makassar', '- Menurut media RRI.co.id, pada 02 Feb 2026, BMKG: Sebagian Wilayah Aceh Malam Ini Diprediksi Hujan', '- Menurut media Qoo10.co.id, pada 05 Feb 2026, Hujan Dominasi Jawa Tengah 4-5 Feb 2026, Waspada Petir di Wilayah Banyumas & Cilacap', '- Menurut media Qoo10.co.id, pada 05 Feb 2026, Waspada Hujan Lebat & Angin Kencang di Jawa Barat 5 Feb 2026, Cek Prakiraan Terbaru BMKG']
news
 ['- Menurut media CNN Indonesia, pada 06 Feb 2026, Peringatan BMKG: Cuaca Ekstrem Mengintai Indonesia Sepekan ke Depan', '- Menurut media CNN Indonesia, pada 06 Feb 2026, Dampak Krisis Iklim, Hujan di Indonesia Makin Ekstrem', '- Menurut media ANTARA News Megapolitan, pada 02 Feb 2026, 19 rumah warga rusak akibat hujan dan angin kencang di Makassar', '- Menurut media RRI.co.id, pada 02 Feb 2026, BMKG: Sebagian Wilayah Aceh Malam Ini Diprediksi Hujan', '- Menurut media Qoo10.co.id, pada 05 Feb 2026, Hujan Dominasi Jawa Tengah 4-5 Feb 2026, Waspada Petir di Wilayah Banyumas & Cilacap', '- Menurut media Qoo10.co.id, pada 05 Feb 2026, Waspada Hujan Lebat & Angin Kencang di Jawa Barat 5 Feb 2026, Cek Prakiraan Terbaru BMKG']
 id 1 [2/44] 2026-02-09 → 2026-02-10 ... total berita 3 | holiday 7
hari besar
 ['Berdekatan dengan hari besar:', '- Lunar New Year (estimated) (17-02-2026)', '', 'Terjadi peristiwa:', '- Menurut media Kompas.tv, pada 10 Feb 2026, Cuaca Ekstrem Hujan Lebat Diprediksi Meluas Sepekan ke Depan, BMKG Ungkap Penyebabnya', '- Menurut media RRI.co.id, pada 09 Feb 2026, BMKG: Waspada, Aceh Malam Ini Kembali Diguyur Hujan', '- Menurut media Beritajateng.tv, pada 10 Feb 2026, Prakiraan Cuaca Semarang Hujan Sedang dan Jateng Selasa 10 Februari 2026']
news
 ['- Menurut media Kompas.tv, pada 10 Feb 2026, Cuaca Ekstrem Hujan Lebat Diprediksi Meluas Sepekan ke Depan, BMKG Ungkap Penyebabnya', '- Menurut media RRI.co.id, pada 09 Feb 2026, BMKG: Waspada, Aceh Malam Ini Kembali Diguyur Hujan', '- Menurut media Beritajateng.tv, pada 10 Feb 2026, Prakiraan Cuaca Semarang Hujan Sedang dan Jateng Selasa 10 Februari 2026']
 id 2 [3/44] 2026-02-20 → 2026-02-20 ...

/home/dimas/.local/lib/python3.10/site-packages/gnews/gnews.py:146: UserWarning: The start and end dates should be at least 1 day apart.
  warnings.warn("The start and end dates should be at least 1 day apart.")

total berita 0 | holiday 2
hari besar
 ['Berdekatan dengan hari besar:', '- Lunar New Year (estimated) (17-02-2026)']
news
 []
 id 3 [4/44] 2026-02-23 → 2026-02-26 ... total berita 8 | holiday 12
hari besar
 ['Berdekatan dengan hari besar:', '- Lunar New Year (estimated) (17-02-2026)', '', 'Terjadi peristiwa:', '- Menurut media Nusadaily, pada 23 Feb 2026, Awas! BMKG Peringatkan Malang Raya dan Jatim Waspada Cuaca Ekstrem', '- Menurut media Beritajateng.tv, pada 24 Feb 2026, Kamis Berpotensi Diguyur Hujan Lebat, BMKG Imbau Masyarakat Tingkatkan Kewaspadaan', '- Menurut media Kompas.tv, pada 24 Feb 2026, Peringatan Dini BMKG 25 26 Februari 2026: Hujan Lebat Mengintai Sejumlah Provinsi, Ini Daftarnya', '- Menurut media Jatimtimes, pada 24 Feb 2026, Bupati Malang Tinjau Dampak Bencana Puting Beliung: Rusak 15 Rumah, Kerugian Puluhan Juta', '- Menurut media Beritajateng.tv, pada 24 Feb 2026, Waspada Hujan Lebat, BMKG Rilis Prakiraan Cuaca Rabu 25 Februari 2026', '- Menurut media mandalikapost.com, pada 25 Feb 2026, Waspada! NTB Dikepung Cuaca Ekstrem Hingga 27 Februari, BMKG ZAM Ingatkan Potensi Hujan Sangat Lebat', '- Menurut media Jatim Hari Ini, pada 25 Feb 2026, Pohon Besar Tumbang Tutup Jalur Ranupani-Malang, Akses Sempat Lumpuh Total', '- Menurut media Beritajateng.tv, pada 24 Feb 2026, Cuaca Indonesia 24 Februari 2026: Sejumlah Wilayah Berpotensi Hujan Lebat hingga Petir']
news
 ['- Menurut media Nusadaily, pada 23 Feb 2026, Awas! BMKG Peringatkan Malang Raya dan Jatim Waspada Cuaca Ekstrem', '- Menurut media Beritajateng.tv, pada 24 Feb 2026, Kamis Berpotensi Diguyur Hujan Lebat, BMKG Imbau Masyarakat Tingkatkan Kewaspadaan', '- Menurut media Kompas.tv, pada 24 Feb 2026, Peringatan Dini BMKG 25 26 Februari 2026: Hujan Lebat Mengintai Sejumlah Provinsi, Ini Daftarnya', '- Menurut media Jatimtimes, pada 24 Feb 2026, Bupati Malang Tinjau Dampak Bencana Puting Beliung: Rusak 15 Rumah, Kerugian Puluhan Juta', '- Menurut media Beritajateng.tv, pada 24 Feb 2026, Waspada Hujan Lebat, BMKG Rilis Prakiraan Cuaca Rabu 25 Februari 2026', '- Menurut media mandalikapost.com, pada 25 Feb 2026, Waspada! NTB Dikepung Cuaca Ekstrem Hingga 27 Februari, BMKG ZAM Ingatkan Potensi Hujan Sangat Lebat', '- Menurut media Jatim Hari Ini, pada 25 Feb 2026, Pohon Besar Tumbang Tutup Jalur Ranupani-Malang, Akses Sempat Lumpuh Total', '- Menurut media Beritajateng.tv, pada 24 Feb 2026, Cuaca Indonesia 24 Februari 2026: Sejumlah Wilayah Berpotensi Hujan Lebat hingga Petir']
 id 4 [5/44] 2026-01-02 → 2026-01-15 ... total berita 10 | holiday 15
hari besar
 ['Berdekatan dengan hari besar:', "- New Year's Day (01-01-2026)", "- Isra' and Mi'raj (estimated) (16-01-2026)", '', 'Terjadi peristiwa:', '- Menurut media MetroTVNews.com, pada 05 Jan 2026, Waspada Cuaca Ekstrem, BMKG Beri Peringatan Hingga 8 Januari 2026', '- Menurut media HARIAN DISWAY, pada 02 Jan 2026, Sepekan Cuaca Ekstrem di Jatim, Berlaku di 38 Kabupaten Kota', '- Menurut media Radar Tuban, pada 08 Jan 2026, Waspada Cuaca Ekstrem! Gelombang Laut di Sejumlah Perairan Indonesia Berpotensi Tembus 6 Meter', '- Menurut media Kompas.com, pada 09 Jan 2026, Peringatan Dini BMKG 9 Januari 2026: Daftar Wilayah Berpotensi Cuaca Ekstrem dan Hujan Lebat', '- Menurut media Tribun Video, pada 10 Jan 2026, Waspada! Cuaca Ekstrem Minggu 11 Januari 2026, 17 Wilayah Terancam Hujan Lebat & Angin Kencang', '- Menurut media Tirto.id, pada 15 Jan 2026, BMKG Deteksi 2 Siklon Tropis Sebabkan Cuaca Ekstrem Jawa-Bali', '- Menurut media CNN Indonesia, pada 02 Jan 2026, Prediksi Cuaca Awal Tahun 2026', '- Menurut media RRI.co.id, pada 03 Jan 2026, BMKG Imbau Dampak Siklon Tropis IGGY', '- Menurut media Bisnis.com, pada 13 Jan 2026, Awal 2026 Sudah 26.318 Warga Jabar Terdampak Bencana Alam', '- Menurut media Kompas.com, pada 08 Jan 2026, BMKG Beri Peringatan Dini Cuaca Ekstrem 8 Januari 2026: Daftar Wilayah Berpotensi Hujan Lebat']
news
 ['- Menurut media MetroTVNews.com, pada 05 Jan 2026, Waspada Cuaca Ekstrem, BMKG Beri Peringatan Hingga 8 Januari 2026', '- Menurut media HARIAN DISWAY, pada 02 Jan 2026, Sepekan Cuaca Ekstrem di Jatim, Berlaku di 38 Kabupaten Kota', '- Menurut media Radar Tuban, pada 08 Jan 2026, Waspada Cuaca Ekstrem! Gelombang Laut di Sejumlah Perairan Indonesia Berpotensi Tembus 6 Meter', '- Menurut media Kompas.com, pada 09 Jan 2026, Peringatan Dini BMKG 9 Januari 2026: Daftar Wilayah Berpotensi Cuaca Ekstrem dan Hujan Lebat', '- Menurut media Tribun Video, pada 10 Jan 2026, Waspada! Cuaca Ekstrem Minggu 11 Januari 2026, 17 Wilayah Terancam Hujan Lebat & Angin Kencang', '- Menurut media Tirto.id, pada 15 Jan 2026, BMKG Deteksi 2 Siklon Tropis Sebabkan Cuaca Ekstrem Jawa-Bali', '- Menurut media CNN Indonesia, pada 02 Jan 2026, Prediksi Cuaca Awal Tahun 2026', '- Menurut media RRI.co.id, pada 03 Jan 2026, BMKG Imbau Dampak Siklon Tropis IGGY', '- Menurut media Bisnis.com, pada 13 Jan 2026, Awal 2026 Sudah 26.318 Warga Jabar Terdampak Bencana Alam', '- Menurut media Kompas.com, pada 08 Jan 2026, BMKG Beri Peringatan Dini Cuaca Ekstrem 8 Januari 2026: Daftar Wilayah Berpotensi Hujan Lebat']
 id 5 [6/44] 2026-01-16 → 2026-01-27 ... total berita 12 | holiday 16
hari besar
 ['Berdekatan dengan hari besar:', "- Isra' and Mi'raj (estimated) (16-01-2026)", '', 'Terjadi peristiwa:', '- Menurut media SinPo.id, pada 25 Jan 2026, BMKG Peringatkan Cuaca Ekstrem Akhir Pekan di Jakarta dan Sejumlah Wilayah', '- Menurut media Antara News jatim, pada 24 Jan 2026, BMKG ungkap penyebab angin kencang di wilayah Malang', '- Menurut media Kompas.com, pada 22 Jan 2026, BMKG Peringatkan Cuaca Ekstrem Saat Puncak Musim Hujan di Jatim', '- Menurut media Tugu Malang ID, pada 24 Jan 2026, Cuaca Ekstrem Akan Melanda Malang hingga Akhir Januari 2026', '- Menurut media beritabuana.co, pada 27 Jan 2026, Waspada dan Siaga! BMKG Ingatkan Potensi Cuaca Ekstrem Picu Banjir Bandang dan Longsor', '- Menurut media Kompas.tv, pada 22 Jan 2026, Peringatan Dini Cuaca 23-24 Januari 2026, BMKG: Waspadai Potensi Hujan Ekstrem di Jakarta-Banten', '- Menurut media Ulasan.co, pada 22 Jan 2026, Cuaca Ekstrem Mengintai Akhir Januari, BMKG Ungkap Wilayah RI yang Paling Berisiko', '- Menurut media Kabar Nusantara, pada 20 Jan 2026, Khofifah Bersama DPRD Jatim Resmikan Dua Perda Penguatan Sektor Perikanan Budidaya dan Penanggulangan Bencana', '- Menurut media Liputan6.com, pada 21 Jan 2026, BMKG Ungkap Potensi Cuaca Ekstrem di Akhir Januari 2026, Kenali Ciri Hoaksnya', '- Menurut media detikcom, pada 23 Jan 2026, Mengapa Jabodetabek Hujan Terus Sepekan Ini? Begini Penjelasan BMKG', '- Menurut media Kompas.com, pada 27 Jan 2026, Waspada, Cuaca Ekstrem Masih Membayangi Wilayah Indonesia', '- Menurut media Kompas.com, pada 21 Jan 2026, Cuaca Ekstrem di Indonesia Sampai Kapan? Ini Jawaban BMKG']
news
 ['- Menurut media SinPo.id, pada 25 Jan 2026, BMKG Peringatkan Cuaca Ekstrem Akhir Pekan di Jakarta dan Sejumlah Wilayah', '- Menurut media Antara News jatim, pada 24 Jan 2026, BMKG ungkap penyebab angin kencang di wilayah Malang', '- Menurut media Kompas.com, pada 22 Jan 2026, BMKG Peringatkan Cuaca Ekstrem Saat Puncak Musim Hujan di Jatim', '- Menurut media Tugu Malang ID, pada 24 Jan 2026, Cuaca Ekstrem Akan Melanda Malang hingga Akhir Januari 2026', '- Menurut media beritabuana.co, pada 27 Jan 2026, Waspada dan Siaga! BMKG Ingatkan Potensi Cuaca Ekstrem Picu Banjir Bandang dan Longsor', '- Menurut media Kompas.tv, pada 22 Jan 2026, Peringatan Dini Cuaca 23-24 Januari 2026, BMKG: Waspadai Potensi Hujan Ekstrem di Jakarta-Banten', '- Menurut media Ulasan.co, pada 22 Jan 2026, Cuaca Ekstrem Mengintai Akhir Januari, BMKG Ungkap Wilayah RI yang Paling Berisiko', '- Menurut media Kabar Nusantara, pada 20 Jan 2026, Khofifah Bersama DPRD Jatim Resmikan Dua Perda Penguatan Sektor Perikanan Budidaya dan Penanggulangan Bencana', '- Menurut media Liputan6.com, pada 21 Jan 2026, BMKG Ungkap Potensi Cuaca Ekstrem di Akhir Januari 2026, Kenali Ciri Hoaksnya', '- Menurut media detikcom, pada 23 Jan 2026, Mengapa Jabodetabek Hujan Terus Sepekan Ini? Begini Penjelasan BMKG', '- Menurut media Kompas.com, pada 27 Jan 2026, Waspada, Cuaca Ekstrem Masih Membayangi Wilayah Indonesia', '- Menurut media Kompas.com, pada 21 Jan 2026, Cuaca Ekstrem di Indonesia Sampai Kapan? Ini Jawaban BMKG']
 id 6 [7/44] 2026-01-30 → 2026-01-30 ...

/home/dimas/.local/lib/python3.10/site-packages/gnews/gnews.py:146: UserWarning: The start and end dates should be at least 1 day apart.
  warnings.warn("The start and end dates should be at least 1 day apart.")

total berita 0 | holiday 0
hari besar
 []
news
 []
 id 7 [8/44] 2026-02-02 → 2026-02-09 ... total berita 7 | holiday 8
hari besar
 ['Terjadi peristiwa:', '- Menurut media Kompas.tv, pada 08 Feb 2026, BMKG Sebut Ada Peringatan Dini Cuaca Ekstrem 9-10 Februari 2026, Waspada Banjir!', '- Menurut media ANTARA News Megapolitan, pada 02 Feb 2026, 19 rumah warga rusak akibat hujan dan angin kencang di Makassar', '- Menurut media RRI.co.id, pada 09 Feb 2026, BMKG: Waspada, Aceh Malam Ini Kembali Diguyur Hujan', '- Menurut media Kompas.tv, pada 08 Feb 2026, Prakiraan Cuaca BMKG Hari Ini Minggu 8 Februari 2026: Jawa dan NTT Waspada Hujan Lebat', '- Menurut media RRI.co.id, pada 02 Feb 2026, BMKG: Sebagian Wilayah Aceh Malam Ini Diprediksi Hujan', '- Menurut media Qoo10.co.id, pada 05 Feb 2026, Hujan Dominasi Jawa Tengah 4-5 Feb 2026, Waspada Petir di Wilayah Banyumas & Cilacap', '- Menurut media Qoo10.co.id, pada 05 Feb 2026, Waspada Hujan Lebat & Angin Kencang di Jawa Barat 5 Feb 2026, Cek Prakiraan Terbaru BMKG']
news
 ['- Menurut media Kompas.tv, pada 08 Feb 2026, BMKG Sebut Ada Peringatan Dini Cuaca Ekstrem 9-10 Februari 2026, Waspada Banjir!', '- Menurut media ANTARA News Megapolitan, pada 02 Feb 2026, 19 rumah warga rusak akibat hujan dan angin kencang di Makassar', '- Menurut media RRI.co.id, pada 09 Feb 2026, BMKG: Waspada, Aceh Malam Ini Kembali Diguyur Hujan', '- Menurut media Kompas.tv, pada 08 Feb 2026, Prakiraan Cuaca BMKG Hari Ini Minggu 8 Februari 2026: Jawa dan NTT Waspada Hujan Lebat', '- Menurut media RRI.co.id, pada 02 Feb 2026, BMKG: Sebagian Wilayah Aceh Malam Ini Diprediksi Hujan', '- Menurut media Qoo10.co.id, pada 05 Feb 2026, Hujan Dominasi Jawa Tengah 4-5 Feb 2026, Waspada Petir di Wilayah Banyumas & Cilacap', '- Menurut media Qoo10.co.id, pada 05 Feb 2026, Waspada Hujan Lebat & Angin Kencang di Jawa Barat 5 Feb 2026, Cek Prakiraan Terbaru BMKG']
 id 8 [9/44] 2026-02-15 → 2026-02-17 ... total berita 4 | holiday 8
hari besar
 ['Berdekatan dengan hari besar:', '- Lunar New Year (estimated) (17-02-2026)', '', 'Terjadi peristiwa:', '- Menurut media RRI.co.id, pada 17 Feb 2026, Harga Pangan Jadi Tantangan Utama Pengendalian Inflasi 2026', '- Menurut media TVRI News, pada 16 Feb 2026, Penentuan 1 Ramadan 2026, BMKG Terjunkan Tim di 37 Lokasi', '- Menurut media RRI.co.id, pada 16 Feb 2026, Cuaca Ekstrim Harga Cabai Melonjak Rp 45.000/Kg', '- Menurut media RRI.co.id, pada 15 Feb 2026, BMKG Ingatkan Potensi Cuaca Ekstrem di Sulawesi Utara']
news
 ['- Menurut media RRI.co.id, pada 17 Feb 2026, Harga Pangan Jadi Tantangan Utama Pengendalian Inflasi 2026', '- Menurut media TVRI News, pada 16 Feb 2026, Penentuan 1 Ramadan 2026, BMKG Terjunkan Tim di 37 Lokasi', '- Menurut media RRI.co.id, pada 16 Feb 2026, Cuaca Ekstrim Harga Cabai Melonjak Rp 45.000/Kg', '- Menurut media RRI.co.id, pada 15 Feb 2026, BMKG Ingatkan Potensi Cuaca Ekstrem di Sulawesi Utara']
 id 9 [10/44] 2026-02-19 → 2026-02-19 ...

/home/dimas/.local/lib/python3.10/site-packages/gnews/gnews.py:146: UserWarning: The start and end dates should be at least 1 day apart.
  warnings.warn("The start and end dates should be at least 1 day apart.")

total berita 1 | holiday 5
hari besar
 ['Berdekatan dengan hari besar:', '- Lunar New Year (estimated) (17-02-2026)', '', 'Terjadi peristiwa:', '- Menurut media Beritajateng.tv, pada 19 Feb 2026, Prakiraan Cuaca 19 Februari 2026 : Waspada Cuaca Ekstrem Jawa Tengah di Wilayah Muria']
news
 ['- Menurut media Beritajateng.tv, pada 19 Feb 2026, Prakiraan Cuaca 19 Februari 2026 : Waspada Cuaca Ekstrem Jawa Tengah di Wilayah Muria']
 id 10 [11/44] 2026-02-21 → 2026-02-26 ... total berita 9 | holiday 13
hari besar
 ['Berdekatan dengan hari besar:', '- Lunar New Year (estimated) (17-02-2026)', '', 'Terjadi peristiwa:', '- Menurut media Nusadaily, pada 23 Feb 2026, Awas! BMKG Peringatkan Malang Raya dan Jatim Waspada Cuaca Ekstrem', '- Menurut media Beritajateng.tv, pada 24 Feb 2026, Kamis Berpotensi Diguyur Hujan Lebat, BMKG Imbau Masyarakat Tingkatkan Kewaspadaan', '- Menurut media Qoo10.co.id, pada 23 Feb 2026, Waspada Sirkulasi Siklonik Picu Hujan Lebat Berpotensi Terjang Jawa Bali Hingga NTT Hari Ini', '- Menurut media Beritajateng.tv, pada 22 Feb 2026, Waspada Cuaca Ekstrem! Ini Prakiraan Lengkap BMKG untuk Senin, 23 Februari 2026', '- Menurut media Beritajateng.tv, pada 22 Feb 2026, Cuaca Minggu 22 Februari 2026: Waspada Hujan Lebat dan Petir di Sejumlah Wilayah', '- Menurut media Beritajateng.tv, pada 24 Feb 2026, Waspada Hujan Lebat, BMKG Rilis Prakiraan Cuaca Rabu 25 Februari 2026', '- Menurut media Jatim Hari Ini, pada 25 Feb 2026, Pohon Besar Tumbang Tutup Jalur Ranupani-Malang, Akses Sempat Lumpuh Total', '- Menurut media VIVA Banyuwangi, pada 23 Feb 2026, Cuaca Ekstrem, KAI Daop 9 Jember Perkuat Infrastruktur dan Siagakan Petugas Ekstra', '- Menurut media Beritajateng.tv, pada 24 Feb 2026, Cuaca Indonesia 24 Februari 2026: Sejumlah Wilayah Berpotensi Hujan Lebat hingga Petir']
news
 ['- Menurut media Nusadaily, pada 23 Feb 2026, Awas! BMKG Peringatkan Malang Raya dan Jatim Waspada Cuaca Ekstrem', '- Menurut media Beritajateng.tv, pada 24 Feb 2026, Kamis Berpotensi Diguyur Hujan Lebat, BMKG Imbau Masyarakat Tingkatkan Kewaspadaan', '- Menurut media Qoo10.co.id, pada 23 Feb 2026, Waspada Sirkulasi Siklonik Picu Hujan Lebat Berpotensi Terjang Jawa Bali Hingga NTT Hari Ini', '- Menurut media Beritajateng.tv, pada 22 Feb 2026, Waspada Cuaca Ekstrem! Ini Prakiraan Lengkap BMKG untuk Senin, 23 Februari 2026', '- Menurut media Beritajateng.tv, pada 22 Feb 2026, Cuaca Minggu 22 Februari 2026: Waspada Hujan Lebat dan Petir di Sejumlah Wilayah', '- Menurut media Beritajateng.tv, pada 24 Feb 2026, Waspada Hujan Lebat, BMKG Rilis Prakiraan Cuaca Rabu 25 Februari 2026', '- Menurut media Jatim Hari Ini, pada 25 Feb 2026, Pohon Besar Tumbang Tutup Jalur Ranupani-Malang, Akses Sempat Lumpuh Total', '- Menurut media VIVA Banyuwangi, pada 23 Feb 2026, Cuaca Ekstrem, KAI Daop 9 Jember Perkuat Infrastruktur dan Siagakan Petugas Ekstra', '- Menurut media Beritajateng.tv, pada 24 Feb 2026, Cuaca Indonesia 24 Februari 2026: Sejumlah Wilayah Berpotensi Hujan Lebat hingga Petir']
 id 11 [12/44] 2026-01-02 → 2026-01-09 ... total berita 10 | holiday 15
hari besar
 ['Berdekatan dengan hari besar:', "- New Year's Day (01-01-2026)", "- Isra' and Mi'raj (estimated) (16-01-2026)", '', 'Terjadi peristiwa:', '- Menurut media MetroTVNews.com, pada 05 Jan 2026, Waspada Cuaca Ekstrem, BMKG Beri Peringatan Hingga 8 Januari 2026', '- Menurut media HARIAN DISWAY, pada 02 Jan 2026, Sepekan Cuaca Ekstrem di Jatim, Berlaku di 38 Kabupaten Kota', '- Menurut media Radar Tuban, pada 08 Jan 2026, Waspada Cuaca Ekstrem! Gelombang Laut di Sejumlah Perairan Indonesia Berpotensi Tembus 6 Meter', '- Menurut media Kompas.com, pada 09 Jan 2026, Peringatan Dini BMKG 9 Januari 2026: Daftar Wilayah Berpotensi Cuaca Ekstrem dan Hujan Lebat', '- Menurut media Kompas.tv, pada 09 Jan 2026, BMKG Keluarkan Peringatan Dini Gelombang Tinggi hingga 4 Meter, Berlaku 10 13 Januari 2026', '- Menurut media CNN Indonesia, pada 02 Jan 2026, Prediksi Cuaca Awal Tahun 2026', '- Menurut media RRI.co.id, pada 03 Jan 2026, BMKG Imbau Dampak Siklon Tropis IGGY', '- Menurut media Liputan6.com, pada 08 Jan 2026, Wamendagri Akhmad Wiyagus Apresiasi Penanganan Banjir Bandang Sitaro', '- Menurut media Kompas.com, pada 05 Jan 2026, BMKG Prediksi Hujan Lebat dan Angin Kencang hingga 8 Januari 2026 akibat Siklon Tropis', '- Menurut media Kompas.com, pada 08 Jan 2026, BMKG Beri Peringatan Dini Cuaca Ekstrem 8 Januari 2026: Daftar Wilayah Berpotensi Hujan Lebat']
news
 ['- Menurut media MetroTVNews.com, pada 05 Jan 2026, Waspada Cuaca Ekstrem, BMKG Beri Peringatan Hingga 8 Januari 2026', '- Menurut media HARIAN DISWAY, pada 02 Jan 2026, Sepekan Cuaca Ekstrem di Jatim, Berlaku di 38 Kabupaten Kota', '- Menurut media Radar Tuban, pada 08 Jan 2026, Waspada Cuaca Ekstrem! Gelombang Laut di Sejumlah Perairan Indonesia Berpotensi Tembus 6 Meter', '- Menurut media Kompas.com, pada 09 Jan 2026, Peringatan Dini BMKG 9 Januari 2026: Daftar Wilayah Berpotensi Cuaca Ekstrem dan Hujan Lebat', '- Menurut media Kompas.tv, pada 09 Jan 2026, BMKG Keluarkan Peringatan Dini Gelombang Tinggi hingga 4 Meter, Berlaku 10 13 Januari 2026', '- Menurut media CNN Indonesia, pada 02 Jan 2026, Prediksi Cuaca Awal Tahun 2026', '- Menurut media RRI.co.id, pada 03 Jan 2026, BMKG Imbau Dampak Siklon Tropis IGGY', '- Menurut media Liputan6.com, pada 08 Jan 2026, Wamendagri Akhmad Wiyagus Apresiasi Penanganan Banjir Bandang Sitaro', '- Menurut media Kompas.com, pada 05 Jan 2026, BMKG Prediksi Hujan Lebat dan Angin Kencang hingga 8 Januari 2026 akibat Siklon Tropis', '- Menurut media Kompas.com, pada 08 Jan 2026, BMKG Beri Peringatan Dini Cuaca Ekstrem 8 Januari 2026: Daftar Wilayah Berpotensi Hujan Lebat']
 id 12 [13/44] 2026-01-11 → 2026-01-24 ... total berita 14 | holiday 18
hari besar
 ['Berdekatan dengan hari besar:', "- Isra' and Mi'raj (estimated) (16-01-2026)", '', 'Terjadi peristiwa:', '- Menurut media beritajatim.com, pada 12 Jan 2026, Cuaca Ekstrem Mengintai Jawa Timur, Termasuk Bojonegoro', '- Menurut media Antara News jatim, pada 24 Jan 2026, BMKG ungkap penyebab angin kencang di wilayah Malang', '- Menurut media Kompas.tv, pada 23 Jan 2026, Indonesia Masih Berpotensi Dihantam Cuaca Ekstrem hingga 29 Januari 2026, BMKG Ungkap Penyebabnya', '- Menurut media MetroTVNews.com, pada 17 Jan 2026, Bibit Siklon Tropis Picu Cuaca Ekstrem di Selatan Indonesia, BMKG Keluarkan Peringatan Dini', '- Menurut media Tugu Malang ID, pada 24 Jan 2026, Cuaca Ekstrem Akan Melanda Malang hingga Akhir Januari 2026', '- Menurut media HARIAN MISTAR, pada 23 Jan 2026, BMKG: Cuaca Ekstrem Belum Berakhir, Hujan Lebat Ancam Indonesia hingga 29 Januari', '- Menurut media Ulasan.co, pada 22 Jan 2026, Cuaca Ekstrem Mengintai Akhir Januari, BMKG Ungkap Wilayah RI yang Paling Berisiko', '- Menurut media Kabar Nusantara, pada 20 Jan 2026, Khofifah Bersama DPRD Jatim Resmikan Dua Perda Penguatan Sektor Perikanan Budidaya dan Penanggulangan Bencana', '- Menurut media Suara Jatim Post, pada 17 Jan 2026, KSOP Probolinggo Perketat Pengawasan Pelayaran Menyusul Peringatan Cuaca Ekstrem BMKG', '- Menurut media Bisnis.com, pada 22 Jan 2026, Prediksi Awal Musim Kemarau 2026, Kapan Hujan Berhenti Tahun Ini?', '- Menurut media Kompas.com, pada 21 Jan 2026, Cuaca Ekstrem di Indonesia Sampai Kapan? Ini Jawaban BMKG', '- Menurut media Tirto.id, pada 15 Jan 2026, BMKG Deteksi 2 Siklon Tropis Sebabkan Cuaca Ekstrem Jawa-Bali', '- Menurut media Kabar Malang Com, pada 18 Jan 2026, Waspada Cuaca Ekstrem Hingga 23 Januari 2026: Peringatan Dini BMKG dan Siklon Tropis Nokaen', '- Menurut media Tirto.id, pada 22 Jan 2026, Musim Hujan Sampai Kapan di 2026? Ini Kata BMKG']
news
 ['- Menurut media beritajatim.com, pada 12 Jan 2026, Cuaca Ekstrem Mengintai Jawa Timur, Termasuk Bojonegoro', '- Menurut media Antara News jatim, pada 24 Jan 2026, BMKG ungkap penyebab angin kencang di wilayah Malang', '- Menurut media Kompas.tv, pada 23 Jan 2026, Indonesia Masih Berpotensi Dihantam Cuaca Ekstrem hingga 29 Januari 2026, BMKG Ungkap Penyebabnya', '- Menurut media MetroTVNews.com, pada 17 Jan 2026, Bibit Siklon Tropis Picu Cuaca Ekstrem di Selatan Indonesia, BMKG Keluarkan Peringatan Dini', '- Menurut media Tugu Malang ID, pada 24 Jan 2026, Cuaca Ekstrem Akan Melanda Malang hingga Akhir Januari 2026', '- Menurut media HARIAN MISTAR, pada 23 Jan 2026, BMKG: Cuaca Ekstrem Belum Berakhir, Hujan Lebat Ancam Indonesia hingga 29 Januari', '- Menurut media Ulasan.co, pada 22 Jan 2026, Cuaca Ekstrem Mengintai Akhir Januari, BMKG Ungkap Wilayah RI yang Paling Berisiko', '- Menurut media Kabar Nusantara, pada 20 Jan 2026, Khofifah Bersama DPRD Jatim Resmikan Dua Perda Penguatan Sektor Perikanan Budidaya dan Penanggulangan Bencana', '- Menurut media Suara Jatim Post, pada 17 Jan 2026, KSOP Probolinggo Perketat Pengawasan Pelayaran Menyusul Peringatan Cuaca Ekstrem BMKG', '- Menurut media Bisnis.com, pada 22 Jan 2026, Prediksi Awal Musim Kemarau 2026, Kapan Hujan Berhenti Tahun Ini?', '- Menurut media Kompas.com, pada 21 Jan 2026, Cuaca Ekstrem di Indonesia Sampai Kapan? Ini Jawaban BMKG', '- Menurut media Tirto.id, pada 15 Jan 2026, BMKG Deteksi 2 Siklon Tropis Sebabkan Cuaca Ekstrem Jawa-Bali', '- Menurut media Kabar Malang Com, pada 18 Jan 2026, Waspada Cuaca Ekstrem Hingga 23 Januari 2026: Peringatan Dini BMKG dan Siklon Tropis Nokaen', '- Menurut media Tirto.id, pada 22 Jan 2026, Musim Hujan Sampai Kapan di 2026? Ini Kata BMKG']
 id 13 [14/44] 2026-01-25 → 2026-01-26 ... total berita 3 | holiday 4
hari besar
 ['Terjadi peristiwa:', '- Menurut media SinPo.id, pada 25 Jan 2026, BMKG Peringatkan Cuaca Ekstrem Akhir Pekan di Jakarta dan Sejumlah Wilayah', '- Menurut media detikNews, pada 26 Jan 2026, Cuaca Makin Ekstrem, Bencana Alam Terus Menghantui Indonesia', '- Menurut media Bisnis.com, pada 26 Jan 2026, BMKG Ingatkan Potensi Angin Kencang di Kuningan Selama Beberapa Hari ke Depan']
news
 ['- Menurut media SinPo.id, pada 25 Jan 2026, BMKG Peringatkan Cuaca Ekstrem Akhir Pekan di Jakarta dan Sejumlah Wilayah', '- Menurut media detikNews, pada 26 Jan 2026, Cuaca Makin Ekstrem, Bencana Alam Terus Menghantui Indonesia', '- Menurut media Bisnis.com, pada 26 Jan 2026, BMKG Ingatkan Potensi Angin Kencang di Kuningan Selama Beberapa Hari ke Depan']
 id 14 [15/44] 2026-02-01 → 2026-02-03 ... total berita 4 | holiday 5
hari besar
 ['Terjadi peristiwa:', '- Menurut media ANTARA News Megapolitan, pada 02 Feb 2026, 19 rumah warga rusak akibat hujan dan angin kencang di Makassar', '- Menurut media RRI.co.id, pada 02 Feb 2026, BMKG: Sebagian Wilayah Aceh Malam Ini Diprediksi Hujan', '- Menurut media Kaltim Post, pada 01 Feb 2026, BMKG Kaltim Warning Cuaca Ekstrem Awal Februari 2026: Berikut yang Harus Diwaspadai', '- Menurut media BisnisUpdate.com, pada 01 Feb 2026, BNPB Tangani Cepat Rangkaian Bencana dalam Dua Hari']
news
 ['- Menurut media ANTARA News Megapolitan, pada 02 Feb 2026, 19 rumah warga rusak akibat hujan dan angin kencang di Makassar', '- Menurut media RRI.co.id, pada 02 Feb 2026, BMKG: Sebagian Wilayah Aceh Malam Ini Diprediksi Hujan', '- Menurut media Kaltim Post, pada 01 Feb 2026, BMKG Kaltim Warning Cuaca Ekstrem Awal Februari 2026: Berikut yang Harus Diwaspadai', '- Menurut media BisnisUpdate.com, pada 01 Feb 2026, BNPB Tangani Cepat Rangkaian Bencana dalam Dua Hari']
 id 15 [16/44] 2026-02-05 → 2026-02-09 ... total berita 5 | holiday 6
hari besar
 ['Terjadi peristiwa:', '- Menurut media Kompas.tv, pada 08 Feb 2026, BMKG Sebut Ada Peringatan Dini Cuaca Ekstrem 9-10 Februari 2026, Waspada Banjir!', '- Menurut media RRI.co.id, pada 09 Feb 2026, BMKG: Waspada, Aceh Malam Ini Kembali Diguyur Hujan', '- Menurut media Kompas.tv, pada 08 Feb 2026, Prakiraan Cuaca BMKG Hari Ini Minggu 8 Februari 2026: Jawa dan NTT Waspada Hujan Lebat', '- Menurut media Qoo10.co.id, pada 05 Feb 2026, Hujan Dominasi Jawa Tengah 4-5 Feb 2026, Waspada Petir di Wilayah Banyumas & Cilacap', '- Menurut media Qoo10.co.id, pada 05 Feb 2026, Waspada Hujan Lebat & Angin Kencang di Jawa Barat 5 Feb 2026, Cek Prakiraan Terbaru BMKG']
news
 ['- Menurut media Kompas.tv, pada 08 Feb 2026, BMKG Sebut Ada Peringatan Dini Cuaca Ekstrem 9-10 Februari 2026, Waspada Banjir!', '- Menurut media RRI.co.id, pada 09 Feb 2026, BMKG: Waspada, Aceh Malam Ini Kembali Diguyur Hujan', '- Menurut media Kompas.tv, pada 08 Feb 2026, Prakiraan Cuaca BMKG Hari Ini Minggu 8 Februari 2026: Jawa dan NTT Waspada Hujan Lebat', '- Menurut media Qoo10.co.id, pada 05 Feb 2026, Hujan Dominasi Jawa Tengah 4-5 Feb 2026, Waspada Petir di Wilayah Banyumas & Cilacap', '- Menurut media Qoo10.co.id, pada 05 Feb 2026, Waspada Hujan Lebat & Angin Kencang di Jawa Barat 5 Feb 2026, Cek Prakiraan Terbaru BMKG']
 id 16 [17/44] 2026-02-11 → 2026-02-12 ... total berita 1 | holiday 5
hari besar
 ['Berdekatan dengan hari besar:', '- Lunar New Year (estimated) (17-02-2026)', '', 'Terjadi peristiwa:', '- Menurut media HarianBasis.co, pada 12 Feb 2026, Longsor dan Banjir Landa Tasikmalaya, Puluhan Warga Mengungsi']
news
 ['- Menurut media HarianBasis.co, pada 12 Feb 2026, Longsor dan Banjir Landa Tasikmalaya, Puluhan Warga Mengungsi']
 id 17 [18/44] 2026-02-15 → 2026-02-15 ...

/home/dimas/.local/lib/python3.10/site-packages/gnews/gnews.py:146: UserWarning: The start and end dates should be at least 1 day apart.
  warnings.warn("The start and end dates should be at least 1 day apart.")

total berita 1 | holiday 5
hari besar
 ['Berdekatan dengan hari besar:', '- Lunar New Year (estimated) (17-02-2026)', '', 'Terjadi peristiwa:', '- Menurut media RRI.co.id, pada 15 Feb 2026, BMKG Ingatkan Potensi Cuaca Ekstrem di Sulawesi Utara']
news
 ['- Menurut media RRI.co.id, pada 15 Feb 2026, BMKG Ingatkan Potensi Cuaca Ekstrem di Sulawesi Utara']
 id 18 [19/44] 2026-02-17 → 2026-02-26 ... total berita 11 | holiday 15
hari besar
 ['Berdekatan dengan hari besar:', '- Lunar New Year (estimated) (17-02-2026)', '', 'Terjadi peristiwa:', '- Menurut media Nusadaily, pada 23 Feb 2026, Awas! BMKG Peringatkan Malang Raya dan Jatim Waspada Cuaca Ekstrem', '- Menurut media Sinergia Mediatama, pada 19 Feb 2026, Waspada Cuaca Ekstrem di Madiun, Sejumlah Rumah Rusak Diterjang Hujan dan Angin Kencang', '- Menurut media Beritajateng.tv, pada 24 Feb 2026, Kamis Berpotensi Diguyur Hujan Lebat, BMKG Imbau Masyarakat Tingkatkan Kewaspadaan', '- Menurut media Jatim Hari Ini, pada 25 Feb 2026, Pohon Besar Tumbang Tutup Jalur Ranupani-Malang, Akses Sempat Lumpuh Total', '- Menurut media VIVA Banyuwangi, pada 23 Feb 2026, Cuaca Ekstrem, KAI Daop 9 Jember Perkuat Infrastruktur dan Siagakan Petugas Ekstra', '- Menurut media Beritajateng.tv, pada 22 Feb 2026, Cuaca Minggu 22 Februari 2026: Waspada Hujan Lebat dan Petir di Sejumlah Wilayah', '- Menurut media Beritajateng.tv, pada 22 Feb 2026, Waspada Cuaca Ekstrem! Ini Prakiraan Lengkap BMKG untuk Senin, 23 Februari 2026', '- Menurut media Beritajateng.tv, pada 20 Feb 2026, Cuaca Jumat, 20 Februari 2026: BMKG Peringatkan Potensi Hujan Lebat di Sejumlah Wilayah', '- Menurut media Beritajateng.tv, pada 19 Feb 2026, Prakiraan Cuaca 19 Februari 2026 : Waspada Cuaca Ekstrem Jawa Tengah di Wilayah Muria', '- Menurut media Beritajateng.tv, pada 24 Feb 2026, Waspada Hujan Lebat, BMKG Rilis Prakiraan Cuaca Rabu 25 Februari 2026', '- Menurut media Beritajateng.tv, pada 24 Feb 2026, Cuaca Indonesia 24 Februari 2026: Sejumlah Wilayah Berpotensi Hujan Lebat hingga Petir']
news
 ['- Menurut media Nusadaily, pada 23 Feb 2026, Awas! BMKG Peringatkan Malang Raya dan Jatim Waspada Cuaca Ekstrem', '- Menurut media Sinergia Mediatama, pada 19 Feb 2026, Waspada Cuaca Ekstrem di Madiun, Sejumlah Rumah Rusak Diterjang Hujan dan Angin Kencang', '- Menurut media Beritajateng.tv, pada 24 Feb 2026, Kamis Berpotensi Diguyur Hujan Lebat, BMKG Imbau Masyarakat Tingkatkan Kewaspadaan', '- Menurut media Jatim Hari Ini, pada 25 Feb 2026, Pohon Besar Tumbang Tutup Jalur Ranupani-Malang, Akses Sempat Lumpuh Total', '- Menurut media VIVA Banyuwangi, pada 23 Feb 2026, Cuaca Ekstrem, KAI Daop 9 Jember Perkuat Infrastruktur dan Siagakan Petugas Ekstra', '- Menurut media Beritajateng.tv, pada 22 Feb 2026, Cuaca Minggu 22 Februari 2026: Waspada Hujan Lebat dan Petir di Sejumlah Wilayah', '- Menurut media Beritajateng.tv, pada 22 Feb 2026, Waspada Cuaca Ekstrem! Ini Prakiraan Lengkap BMKG untuk Senin, 23 Februari 2026', '- Menurut media Beritajateng.tv, pada 20 Feb 2026, Cuaca Jumat, 20 Februari 2026: BMKG Peringatkan Potensi Hujan Lebat di Sejumlah Wilayah', '- Menurut media Beritajateng.tv, pada 19 Feb 2026, Prakiraan Cuaca 19 Februari 2026 : Waspada Cuaca Ekstrem Jawa Tengah di Wilayah Muria', '- Menurut media Beritajateng.tv, pada 24 Feb 2026, Waspada Hujan Lebat, BMKG Rilis Prakiraan Cuaca Rabu 25 Februari 2026', '- Menurut media Beritajateng.tv, pada 24 Feb 2026, Cuaca Indonesia 24 Februari 2026: Sejumlah Wilayah Berpotensi Hujan Lebat hingga Petir']
 id 19 [20/44] 2026-01-07 → 2026-01-09 ... total berita 7 | holiday 12
hari besar
 ['Berdekatan dengan hari besar:', "- New Year's Day (01-01-2026)", "- Isra' and Mi'raj (estimated) (16-01-2026)", '', 'Terjadi peristiwa:', '- Menurut media Liputan6.com, pada 07 Jan 2026, Waspada Cuaca Ekstrem, Harga Pangan Berpotensi Melonjak Jelang Ramadan 2026', '- Menurut media Radar Tuban, pada 08 Jan 2026, Waspada Cuaca Ekstrem! Gelombang Laut di Sejumlah Perairan Indonesia Berpotensi Tembus 6 Meter', '- Menurut media Kompas.com, pada 09 Jan 2026, Peringatan Dini BMKG 9 Januari 2026: Daftar Wilayah Berpotensi Cuaca Ekstrem dan Hujan Lebat', '- Menurut media Kompas.tv, pada 09 Jan 2026, BMKG Keluarkan Peringatan Dini Gelombang Tinggi hingga 4 Meter, Berlaku 10 13 Januari 2026', '- Menurut media Kompas.com, pada 08 Jan 2026, BMKG Beri Peringatan Dini Cuaca Ekstrem 8 Januari 2026: Daftar Wilayah Berpotensi Hujan Lebat', '- Menurut media Jawa Pos, pada 07 Jan 2026, Cuaca Ekstrem, KSOP Khusus Batam Keluarkan Peringatan Dini Keselamatan Pelayaran', '- Menurut media Liputan6.com, pada 08 Jan 2026, Wamendagri Akhmad Wiyagus Apresiasi Penanganan Banjir Bandang Sitaro']
news
 ['- Menurut media Liputan6.com, pada 07 Jan 2026, Waspada Cuaca Ekstrem, Harga Pangan Berpotensi Melonjak Jelang Ramadan 2026', '- Menurut media Radar Tuban, pada 08 Jan 2026, Waspada Cuaca Ekstrem! Gelombang Laut di Sejumlah Perairan Indonesia Berpotensi Tembus 6 Meter', '- Menurut media Kompas.com, pada 09 Jan 2026, Peringatan Dini BMKG 9 Januari 2026: Daftar Wilayah Berpotensi Cuaca Ekstrem dan Hujan Lebat', '- Menurut media Kompas.tv, pada 09 Jan 2026, BMKG Keluarkan Peringatan Dini Gelombang Tinggi hingga 4 Meter, Berlaku 10 13 Januari 2026', '- Menurut media Kompas.com, pada 08 Jan 2026, BMKG Beri Peringatan Dini Cuaca Ekstrem 8 Januari 2026: Daftar Wilayah Berpotensi Hujan Lebat', '- Menurut media Jawa Pos, pada 07 Jan 2026, Cuaca Ekstrem, KSOP Khusus Batam Keluarkan Peringatan Dini Keselamatan Pelayaran', '- Menurut media Liputan6.com, pada 08 Jan 2026, Wamendagri Akhmad Wiyagus Apresiasi Penanganan Banjir Bandang Sitaro']
 id 20 [21/44] 2026-01-12 → 2026-01-14 ... total berita 7 | holiday 11
hari besar
 ['Berdekatan dengan hari besar:', "- Isra' and Mi'raj (estimated) (16-01-2026)", '', 'Terjadi peristiwa:', '- Menurut media Bisnis.com, pada 13 Jan 2026, Awal 2026 Sudah 26.318 Warga Jabar Terdampak Bencana Alam', '- Menurut media ANTARA News Jateng, pada 12 Jan 2026, BMKG imbau waspadai cuaca ekstrem tiga hari ke depan di wilayah Pantura', '- Menurut media MetroTVNews.com, pada 12 Jan 2026, BMKG: Waspada Hujan Petir di Jaksel dan Jaktim Hari Ini', '- Menurut media Tribunbanyumas.com, pada 13 Jan 2026, Waspada! Cuaca Ekstrem Hujan Lebat dan Angin Kencang Berpotensi Terjadi di Cilacap Hingga Awal Maret', '- Menurut media Suara Ternate, pada 14 Jan 2026, Potensi Cuaca Ekstrim, Gubernur Sherly Minta Masyarakat Waspada dan Tunda Perjalanan', '- Menurut media KONTAN, pada 13 Jan 2026, Hujan Jabodetabek Belum Berakhir: BMKG Prediksi Cuaca Ekstrem 6 Hari', '- Menurut media RRI.co.id, pada 13 Jan 2026, Harga Tomat Melonjak, Cabai Turun di PKL Kendari']
news
 ['- Menurut media Bisnis.com, pada 13 Jan 2026, Awal 2026 Sudah 26.318 Warga Jabar Terdampak Bencana Alam', '- Menurut media ANTARA News Jateng, pada 12 Jan 2026, BMKG imbau waspadai cuaca ekstrem tiga hari ke depan di wilayah Pantura', '- Menurut media MetroTVNews.com, pada 12 Jan 2026, BMKG: Waspada Hujan Petir di Jaksel dan Jaktim Hari Ini', '- Menurut media Tribunbanyumas.com, pada 13 Jan 2026, Waspada! Cuaca Ekstrem Hujan Lebat dan Angin Kencang Berpotensi Terjadi di Cilacap Hingga Awal Maret', '- Menurut media Suara Ternate, pada 14 Jan 2026, Potensi Cuaca Ekstrim, Gubernur Sherly Minta Masyarakat Waspada dan Tunda Perjalanan', '- Menurut media KONTAN, pada 13 Jan 2026, Hujan Jabodetabek Belum Berakhir: BMKG Prediksi Cuaca Ekstrem 6 Hari', '- Menurut media RRI.co.id, pada 13 Jan 2026, Harga Tomat Melonjak, Cabai Turun di PKL Kendari']
 id 21 [22/44] 2026-02-05 → 2026-02-05 ...

/home/dimas/.local/lib/python3.10/site-packages/gnews/gnews.py:146: UserWarning: The start and end dates should be at least 1 day apart.
  warnings.warn("The start and end dates should be at least 1 day apart.")

total berita 1 | holiday 2
hari besar
 ['Terjadi peristiwa:', '- Menurut media Qoo10.co.id, pada 05 Feb 2026, Waspada Hujan Lebat & Angin Kencang di Jawa Barat 5 Feb 2026, Cek Prakiraan Terbaru BMKG']
news
 ['- Menurut media Qoo10.co.id, pada 05 Feb 2026, Waspada Hujan Lebat & Angin Kencang di Jawa Barat 5 Feb 2026, Cek Prakiraan Terbaru BMKG']
 id 22 [23/44] 2026-02-10 → 2026-02-10 ...

/home/dimas/.local/lib/python3.10/site-packages/gnews/gnews.py:146: UserWarning: The start and end dates should be at least 1 day apart.
  warnings.warn("The start and end dates should be at least 1 day apart.")

total berita 2 | holiday 6
hari besar
 ['Berdekatan dengan hari besar:', '- Lunar New Year (estimated) (17-02-2026)', '', 'Terjadi peristiwa:', '- Menurut media Kompas.tv, pada 10 Feb 2026, Cuaca Ekstrem Hujan Lebat Diprediksi Meluas Sepekan ke Depan, BMKG Ungkap Penyebabnya', '- Menurut media Qoo10.co.id, pada 10 Feb 2026, Cuaca Jatim Selasa: Berawan Tebal dan Hujan Petir Pagi hingga Sore, Waspada Angin Kencang']
news
 ['- Menurut media Kompas.tv, pada 10 Feb 2026, Cuaca Ekstrem Hujan Lebat Diprediksi Meluas Sepekan ke Depan, BMKG Ungkap Penyebabnya', '- Menurut media Qoo10.co.id, pada 10 Feb 2026, Cuaca Jatim Selasa: Berawan Tebal dan Hujan Petir Pagi hingga Sore, Waspada Angin Kencang']
 id 23 [24/44] 2026-02-12 → 2026-02-13 ... total berita 1 | holiday 5
hari besar
 ['Berdekatan dengan hari besar:', '- Lunar New Year (estimated) (17-02-2026)', '', 'Terjadi peristiwa:', '- Menurut media HarianBasis.co, pada 12 Feb 2026, Longsor dan Banjir Landa Tasikmalaya, Puluhan Warga Mengungsi']
news
 ['- Menurut media HarianBasis.co, pada 12 Feb 2026, Longsor dan Banjir Landa Tasikmalaya, Puluhan Warga Mengungsi']
 id 24 [25/44] 2026-02-18 → 2026-02-18 ...

/home/dimas/.local/lib/python3.10/site-packages/gnews/gnews.py:146: UserWarning: The start and end dates should be at least 1 day apart.
  warnings.warn("The start and end dates should be at least 1 day apart.")

total berita 0 | holiday 2
hari besar
 ['Berdekatan dengan hari besar:', '- Lunar New Year (estimated) (17-02-2026)']
news
 []
 id 25 [26/44] 2026-02-20 → 2026-02-20 ...

/home/dimas/.local/lib/python3.10/site-packages/gnews/gnews.py:146: UserWarning: The start and end dates should be at least 1 day apart.
  warnings.warn("The start and end dates should be at least 1 day apart.")

total berita 0 | holiday 2
hari besar
 ['Berdekatan dengan hari besar:', '- Lunar New Year (estimated) (17-02-2026)']
news
 []
 id 26 [27/44] 2026-02-23 → 2026-02-26 ... total berita 8 | holiday 12
hari besar
 ['Berdekatan dengan hari besar:', '- Lunar New Year (estimated) (17-02-2026)', '', 'Terjadi peristiwa:', '- Menurut media Nusadaily, pada 23 Feb 2026, Awas! BMKG Peringatkan Malang Raya dan Jatim Waspada Cuaca Ekstrem', '- Menurut media Beritajateng.tv, pada 24 Feb 2026, Kamis Berpotensi Diguyur Hujan Lebat, BMKG Imbau Masyarakat Tingkatkan Kewaspadaan', '- Menurut media Kompas.tv, pada 24 Feb 2026, Peringatan Dini BMKG 25 26 Februari 2026: Hujan Lebat Mengintai Sejumlah Provinsi, Ini Daftarnya', '- Menurut media Jatimtimes, pada 24 Feb 2026, Bupati Malang Tinjau Dampak Bencana Puting Beliung: Rusak 15 Rumah, Kerugian Puluhan Juta', '- Menurut media Beritajateng.tv, pada 24 Feb 2026, Waspada Hujan Lebat, BMKG Rilis Prakiraan Cuaca Rabu 25 Februari 2026', '- Menurut media mandalikapost.com, pada 25 Feb 2026, Waspada! NTB Dikepung Cuaca Ekstrem Hingga 27 Februari, BMKG ZAM Ingatkan Potensi Hujan Sangat Lebat', '- Menurut media Jatim Hari Ini, pada 25 Feb 2026, Pohon Besar Tumbang Tutup Jalur Ranupani-Malang, Akses Sempat Lumpuh Total', '- Menurut media Beritajateng.tv, pada 24 Feb 2026, Cuaca Indonesia 24 Februari 2026: Sejumlah Wilayah Berpotensi Hujan Lebat hingga Petir']
news
 ['- Menurut media Nusadaily, pada 23 Feb 2026, Awas! BMKG Peringatkan Malang Raya dan Jatim Waspada Cuaca Ekstrem', '- Menurut media Beritajateng.tv, pada 24 Feb 2026, Kamis Berpotensi Diguyur Hujan Lebat, BMKG Imbau Masyarakat Tingkatkan Kewaspadaan', '- Menurut media Kompas.tv, pada 24 Feb 2026, Peringatan Dini BMKG 25 26 Februari 2026: Hujan Lebat Mengintai Sejumlah Provinsi, Ini Daftarnya', '- Menurut media Jatimtimes, pada 24 Feb 2026, Bupati Malang Tinjau Dampak Bencana Puting Beliung: Rusak 15 Rumah, Kerugian Puluhan Juta', '- Menurut media Beritajateng.tv, pada 24 Feb 2026, Waspada Hujan Lebat, BMKG Rilis Prakiraan Cuaca Rabu 25 Februari 2026', '- Menurut media mandalikapost.com, pada 25 Feb 2026, Waspada! NTB Dikepung Cuaca Ekstrem Hingga 27 Februari, BMKG ZAM Ingatkan Potensi Hujan Sangat Lebat', '- Menurut media Jatim Hari Ini, pada 25 Feb 2026, Pohon Besar Tumbang Tutup Jalur Ranupani-Malang, Akses Sempat Lumpuh Total', '- Menurut media Beritajateng.tv, pada 24 Feb 2026, Cuaca Indonesia 24 Februari 2026: Sejumlah Wilayah Berpotensi Hujan Lebat hingga Petir']
 id 27 [28/44] 2026-01-02 → 2026-01-14 ... total berita 10 | holiday 15
hari besar
 ['Berdekatan dengan hari besar:', "- New Year's Day (01-01-2026)", "- Isra' and Mi'raj (estimated) (16-01-2026)", '', 'Terjadi peristiwa:', '- Menurut media Liputan6.com, pada 07 Jan 2026, Waspada Cuaca Ekstrem, Harga Pangan Berpotensi Melonjak Jelang Ramadan 2026', '- Menurut media beritajatim.com, pada 12 Jan 2026, Cuaca Ekstrem Mengintai Jawa Timur, Termasuk Bojonegoro', '- Menurut media HARIAN DISWAY, pada 02 Jan 2026, Sepekan Cuaca Ekstrem di Jatim, Berlaku di 38 Kabupaten Kota', '- Menurut media Radar Tuban, pada 08 Jan 2026, Waspada Cuaca Ekstrem! Gelombang Laut di Sejumlah Perairan Indonesia Berpotensi Tembus 6 Meter', '- Menurut media Kompas.com, pada 09 Jan 2026, Peringatan Dini BMKG 9 Januari 2026: Daftar Wilayah Berpotensi Cuaca Ekstrem dan Hujan Lebat', '- Menurut media Tribun Video, pada 10 Jan 2026, Waspada! Cuaca Ekstrem Minggu 11 Januari 2026, 17 Wilayah Terancam Hujan Lebat & Angin Kencang', '- Menurut media CNN Indonesia, pada 02 Jan 2026, Prediksi Cuaca Awal Tahun 2026', '- Menurut media RRI.co.id, pada 03 Jan 2026, BMKG Imbau Dampak Siklon Tropis IGGY', '- Menurut media Bisnis.com, pada 13 Jan 2026, Awal 2026 Sudah 26.318 Warga Jabar Terdampak Bencana Alam', '- Menurut media Kompas.com, pada 08 Jan 2026, BMKG Beri Peringatan Dini Cuaca Ekstrem 8 Januari 2026: Daftar Wilayah Berpotensi Hujan Lebat']
news
 ['- Menurut media Liputan6.com, pada 07 Jan 2026, Waspada Cuaca Ekstrem, Harga Pangan Berpotensi Melonjak Jelang Ramadan 2026', '- Menurut media beritajatim.com, pada 12 Jan 2026, Cuaca Ekstrem Mengintai Jawa Timur, Termasuk Bojonegoro', '- Menurut media HARIAN DISWAY, pada 02 Jan 2026, Sepekan Cuaca Ekstrem di Jatim, Berlaku di 38 Kabupaten Kota', '- Menurut media Radar Tuban, pada 08 Jan 2026, Waspada Cuaca Ekstrem! Gelombang Laut di Sejumlah Perairan Indonesia Berpotensi Tembus 6 Meter', '- Menurut media Kompas.com, pada 09 Jan 2026, Peringatan Dini BMKG 9 Januari 2026: Daftar Wilayah Berpotensi Cuaca Ekstrem dan Hujan Lebat', '- Menurut media Tribun Video, pada 10 Jan 2026, Waspada! Cuaca Ekstrem Minggu 11 Januari 2026, 17 Wilayah Terancam Hujan Lebat & Angin Kencang', '- Menurut media CNN Indonesia, pada 02 Jan 2026, Prediksi Cuaca Awal Tahun 2026', '- Menurut media RRI.co.id, pada 03 Jan 2026, BMKG Imbau Dampak Siklon Tropis IGGY', '- Menurut media Bisnis.com, pada 13 Jan 2026, Awal 2026 Sudah 26.318 Warga Jabar Terdampak Bencana Alam', '- Menurut media Kompas.com, pada 08 Jan 2026, BMKG Beri Peringatan Dini Cuaca Ekstrem 8 Januari 2026: Daftar Wilayah Berpotensi Hujan Lebat']
 id 28 [29/44] 2026-01-17 → 2026-01-27 ... total berita 11 | holiday 15
hari besar
 ['Berdekatan dengan hari besar:', "- Isra' and Mi'raj (estimated) (16-01-2026)", '', 'Terjadi peristiwa:', '- Menurut media SinPo.id, pada 25 Jan 2026, BMKG Peringatkan Cuaca Ekstrem Akhir Pekan di Jakarta dan Sejumlah Wilayah', '- Menurut media Antara News jatim, pada 24 Jan 2026, BMKG ungkap penyebab angin kencang di wilayah Malang', '- Menurut media Kompas.com, pada 22 Jan 2026, BMKG Peringatkan Cuaca Ekstrem Saat Puncak Musim Hujan di Jatim', '- Menurut media Tugu Malang ID, pada 24 Jan 2026, Cuaca Ekstrem Akan Melanda Malang hingga Akhir Januari 2026', '- Menurut media beritabuana.co, pada 27 Jan 2026, Waspada dan Siaga! BMKG Ingatkan Potensi Cuaca Ekstrem Picu Banjir Bandang dan Longsor', '- Menurut media Ulasan.co, pada 22 Jan 2026, Cuaca Ekstrem Mengintai Akhir Januari, BMKG Ungkap Wilayah RI yang Paling Berisiko', '- Menurut media Kabar Nusantara, pada 20 Jan 2026, Khofifah Bersama DPRD Jatim Resmikan Dua Perda Penguatan Sektor Perikanan Budidaya dan Penanggulangan Bencana', '- Menurut media Liputan6.com, pada 21 Jan 2026, BMKG Ungkap Potensi Cuaca Ekstrem di Akhir Januari 2026, Kenali Ciri Hoaksnya', '- Menurut media detikcom, pada 23 Jan 2026, Mengapa Jabodetabek Hujan Terus Sepekan Ini? Begini Penjelasan BMKG', '- Menurut media Kompas.com, pada 27 Jan 2026, Waspada, Cuaca Ekstrem Masih Membayangi Wilayah Indonesia', '- Menurut media Kompas.com, pada 21 Jan 2026, Cuaca Ekstrem di Indonesia Sampai Kapan? Ini Jawaban BMKG']
news
 ['- Menurut media SinPo.id, pada 25 Jan 2026, BMKG Peringatkan Cuaca Ekstrem Akhir Pekan di Jakarta dan Sejumlah Wilayah', '- Menurut media Antara News jatim, pada 24 Jan 2026, BMKG ungkap penyebab angin kencang di wilayah Malang', '- Menurut media Kompas.com, pada 22 Jan 2026, BMKG Peringatkan Cuaca Ekstrem Saat Puncak Musim Hujan di Jatim', '- Menurut media Tugu Malang ID, pada 24 Jan 2026, Cuaca Ekstrem Akan Melanda Malang hingga Akhir Januari 2026', '- Menurut media beritabuana.co, pada 27 Jan 2026, Waspada dan Siaga! BMKG Ingatkan Potensi Cuaca Ekstrem Picu Banjir Bandang dan Longsor', '- Menurut media Ulasan.co, pada 22 Jan 2026, Cuaca Ekstrem Mengintai Akhir Januari, BMKG Ungkap Wilayah RI yang Paling Berisiko', '- Menurut media Kabar Nusantara, pada 20 Jan 2026, Khofifah Bersama DPRD Jatim Resmikan Dua Perda Penguatan Sektor Perikanan Budidaya dan Penanggulangan Bencana', '- Menurut media Liputan6.com, pada 21 Jan 2026, BMKG Ungkap Potensi Cuaca Ekstrem di Akhir Januari 2026, Kenali Ciri Hoaksnya', '- Menurut media detikcom, pada 23 Jan 2026, Mengapa Jabodetabek Hujan Terus Sepekan Ini? Begini Penjelasan BMKG', '- Menurut media Kompas.com, pada 27 Jan 2026, Waspada, Cuaca Ekstrem Masih Membayangi Wilayah Indonesia', '- Menurut media Kompas.com, pada 21 Jan 2026, Cuaca Ekstrem di Indonesia Sampai Kapan? Ini Jawaban BMKG']
 id 29 [30/44] 2026-01-29 → 2026-02-03 ... total berita 9 | holiday 10
hari besar
 ['Terjadi peristiwa:', '- Menurut media Kompas.com, pada 29 Jan 2026, Cuaca Ekstrem di Indonesia Diprediksi hingga Maret 2026, Ini Kata BMKG', '- Menurut media Tribun Video, pada 29 Jan 2026, Waspada Cuaca Ekstrem, BMKG Ini Wilayah yang Akan Hujan Lebat pada Kamis 30 Januari 2026', '- Menurut media tvOneNews, pada 29 Jan 2026, Jawa Barat Status Awas, BMKG Rilis Peringatan Dini Cuaca Ekstrem 27-29 Januari 2026', '- Menurut media 20detik, pada 31 Jan 2026, Video Prospek Cuaca hingga 5 Februari: Babel, Jateng & Jatim Hujan Lebat', '- Menurut media ANTARA News Megapolitan, pada 02 Feb 2026, 19 rumah warga rusak akibat hujan dan angin kencang di Makassar', '- Menurut media RRI.co.id, pada 02 Feb 2026, BMKG: Sebagian Wilayah Aceh Malam Ini Diprediksi Hujan', '- Menurut media RRI.co.id, pada 29 Jan 2026, BPBD Talaud Imbau Masyarakat Waspada Guaca Ekstrim', '- Menurut media Kaltim Post, pada 01 Feb 2026, BMKG Kaltim Warning Cuaca Ekstrem Awal Februari 2026: Berikut yang Harus Diwaspadai', '- Menurut media BisnisUpdate.com, pada 01 Feb 2026, BNPB Tangani Cepat Rangkaian Bencana dalam Dua Hari']
news
 ['- Menurut media Kompas.com, pada 29 Jan 2026, Cuaca Ekstrem di Indonesia Diprediksi hingga Maret 2026, Ini Kata BMKG', '- Menurut media Tribun Video, pada 29 Jan 2026, Waspada Cuaca Ekstrem, BMKG Ini Wilayah yang Akan Hujan Lebat pada Kamis 30 Januari 2026', '- Menurut media tvOneNews, pada 29 Jan 2026, Jawa Barat Status Awas, BMKG Rilis Peringatan Dini Cuaca Ekstrem 27-29 Januari 2026', '- Menurut media 20detik, pada 31 Jan 2026, Video Prospek Cuaca hingga 5 Februari: Babel, Jateng & Jatim Hujan Lebat', '- Menurut media ANTARA News Megapolitan, pada 02 Feb 2026, 19 rumah warga rusak akibat hujan dan angin kencang di Makassar', '- Menurut media RRI.co.id, pada 02 Feb 2026, BMKG: Sebagian Wilayah Aceh Malam Ini Diprediksi Hujan', '- Menurut media RRI.co.id, pada 29 Jan 2026, BPBD Talaud Imbau Masyarakat Waspada Guaca Ekstrim', '- Menurut media Kaltim Post, pada 01 Feb 2026, BMKG Kaltim Warning Cuaca Ekstrem Awal Februari 2026: Berikut yang Harus Diwaspadai', '- Menurut media BisnisUpdate.com, pada 01 Feb 2026, BNPB Tangani Cepat Rangkaian Bencana dalam Dua Hari']
 id 30 [31/44] 2026-02-05 → 2026-02-06 ... total berita 4 | holiday 5
hari besar
 ['Terjadi peristiwa:', '- Menurut media CNN Indonesia, pada 06 Feb 2026, Peringatan BMKG: Cuaca Ekstrem Mengintai Indonesia Sepekan ke Depan', '- Menurut media CNN Indonesia, pada 06 Feb 2026, Dampak Krisis Iklim, Hujan di Indonesia Makin Ekstrem', '- Menurut media Qoo10.co.id, pada 05 Feb 2026, Hujan Dominasi Jawa Tengah 4-5 Feb 2026, Waspada Petir di Wilayah Banyumas & Cilacap', '- Menurut media Qoo10.co.id, pada 05 Feb 2026, Waspada Hujan Lebat & Angin Kencang di Jawa Barat 5 Feb 2026, Cek Prakiraan Terbaru BMKG']
news
 ['- Menurut media CNN Indonesia, pada 06 Feb 2026, Peringatan BMKG: Cuaca Ekstrem Mengintai Indonesia Sepekan ke Depan', '- Menurut media CNN Indonesia, pada 06 Feb 2026, Dampak Krisis Iklim, Hujan di Indonesia Makin Ekstrem', '- Menurut media Qoo10.co.id, pada 05 Feb 2026, Hujan Dominasi Jawa Tengah 4-5 Feb 2026, Waspada Petir di Wilayah Banyumas & Cilacap', '- Menurut media Qoo10.co.id, pada 05 Feb 2026, Waspada Hujan Lebat & Angin Kencang di Jawa Barat 5 Feb 2026, Cek Prakiraan Terbaru BMKG']
 id 31 [32/44] 2026-02-09 → 2026-02-14 ... total berita 4 | holiday 8
hari besar
 ['Berdekatan dengan hari besar:', '- Lunar New Year (estimated) (17-02-2026)', '', 'Terjadi peristiwa:', '- Menurut media Kompas.tv, pada 10 Feb 2026, Cuaca Ekstrem Hujan Lebat Diprediksi Meluas Sepekan ke Depan, BMKG Ungkap Penyebabnya', '- Menurut media RRI.co.id, pada 09 Feb 2026, BMKG: Waspada, Aceh Malam Ini Kembali Diguyur Hujan', '- Menurut media HarianBasis.co, pada 12 Feb 2026, Longsor dan Banjir Landa Tasikmalaya, Puluhan Warga Mengungsi', '- Menurut media Beritajateng.tv, pada 10 Feb 2026, Prakiraan Cuaca Semarang Hujan Sedang dan Jateng Selasa 10 Februari 2026']
news
 ['- Menurut media Kompas.tv, pada 10 Feb 2026, Cuaca Ekstrem Hujan Lebat Diprediksi Meluas Sepekan ke Depan, BMKG Ungkap Penyebabnya', '- Menurut media RRI.co.id, pada 09 Feb 2026, BMKG: Waspada, Aceh Malam Ini Kembali Diguyur Hujan', '- Menurut media HarianBasis.co, pada 12 Feb 2026, Longsor dan Banjir Landa Tasikmalaya, Puluhan Warga Mengungsi', '- Menurut media Beritajateng.tv, pada 10 Feb 2026, Prakiraan Cuaca Semarang Hujan Sedang dan Jateng Selasa 10 Februari 2026']
 id 32 [33/44] 2026-02-16 → 2026-02-26 ... total berita 11 | holiday 15
hari besar
 ['Berdekatan dengan hari besar:', '- Lunar New Year (estimated) (17-02-2026)', '', 'Terjadi peristiwa:', '- Menurut media Nusadaily, pada 23 Feb 2026, Awas! BMKG Peringatkan Malang Raya dan Jatim Waspada Cuaca Ekstrem', '- Menurut media Sinergia Mediatama, pada 19 Feb 2026, Waspada Cuaca Ekstrem di Madiun, Sejumlah Rumah Rusak Diterjang Hujan dan Angin Kencang', '- Menurut media RRI.co.id, pada 16 Feb 2026, Cuaca Ekstrim Harga Cabai Melonjak Rp 45.000/Kg', '- Menurut media Beritajateng.tv, pada 24 Feb 2026, Kamis Berpotensi Diguyur Hujan Lebat, BMKG Imbau Masyarakat Tingkatkan Kewaspadaan', '- Menurut media VIVA Banyuwangi, pada 23 Feb 2026, Cuaca Ekstrem, KAI Daop 9 Jember Perkuat Infrastruktur dan Siagakan Petugas Ekstra', '- Menurut media Beritajateng.tv, pada 22 Feb 2026, Cuaca Minggu 22 Februari 2026: Waspada Hujan Lebat dan Petir di Sejumlah Wilayah', '- Menurut media Beritajateng.tv, pada 22 Feb 2026, Waspada Cuaca Ekstrem! Ini Prakiraan Lengkap BMKG untuk Senin, 23 Februari 2026', '- Menurut media Beritajateng.tv, pada 20 Feb 2026, Cuaca Jumat, 20 Februari 2026: BMKG Peringatkan Potensi Hujan Lebat di Sejumlah Wilayah', '- Menurut media Beritajateng.tv, pada 19 Feb 2026, Prakiraan Cuaca 19 Februari 2026 : Waspada Cuaca Ekstrem Jawa Tengah di Wilayah Muria', '- Menurut media Beritajateng.tv, pada 24 Feb 2026, Waspada Hujan Lebat, BMKG Rilis Prakiraan Cuaca Rabu 25 Februari 2026', '- Menurut media Beritajateng.tv, pada 24 Feb 2026, Cuaca Indonesia 24 Februari 2026: Sejumlah Wilayah Berpotensi Hujan Lebat hingga Petir']
news
 ['- Menurut media Nusadaily, pada 23 Feb 2026, Awas! BMKG Peringatkan Malang Raya dan Jatim Waspada Cuaca Ekstrem', '- Menurut media Sinergia Mediatama, pada 19 Feb 2026, Waspada Cuaca Ekstrem di Madiun, Sejumlah Rumah Rusak Diterjang Hujan dan Angin Kencang', '- Menurut media RRI.co.id, pada 16 Feb 2026, Cuaca Ekstrim Harga Cabai Melonjak Rp 45.000/Kg', '- Menurut media Beritajateng.tv, pada 24 Feb 2026, Kamis Berpotensi Diguyur Hujan Lebat, BMKG Imbau Masyarakat Tingkatkan Kewaspadaan', '- Menurut media VIVA Banyuwangi, pada 23 Feb 2026, Cuaca Ekstrem, KAI Daop 9 Jember Perkuat Infrastruktur dan Siagakan Petugas Ekstra', '- Menurut media Beritajateng.tv, pada 22 Feb 2026, Cuaca Minggu 22 Februari 2026: Waspada Hujan Lebat dan Petir di Sejumlah Wilayah', '- Menurut media Beritajateng.tv, pada 22 Feb 2026, Waspada Cuaca Ekstrem! Ini Prakiraan Lengkap BMKG untuk Senin, 23 Februari 2026', '- Menurut media Beritajateng.tv, pada 20 Feb 2026, Cuaca Jumat, 20 Februari 2026: BMKG Peringatkan Potensi Hujan Lebat di Sejumlah Wilayah', '- Menurut media Beritajateng.tv, pada 19 Feb 2026, Prakiraan Cuaca 19 Februari 2026 : Waspada Cuaca Ekstrem Jawa Tengah di Wilayah Muria', '- Menurut media Beritajateng.tv, pada 24 Feb 2026, Waspada Hujan Lebat, BMKG Rilis Prakiraan Cuaca Rabu 25 Februari 2026', '- Menurut media Beritajateng.tv, pada 24 Feb 2026, Cuaca Indonesia 24 Februari 2026: Sejumlah Wilayah Berpotensi Hujan Lebat hingga Petir']
 id 33 [34/44] 2026-01-02 → 2026-01-08 ... total berita 10 | holiday 14
hari besar
 ['Berdekatan dengan hari besar:', "- New Year's Day (01-01-2026)", '', 'Terjadi peristiwa:', '- Menurut media Liputan6.com, pada 07 Jan 2026, Waspada Cuaca Ekstrem, Harga Pangan Berpotensi Melonjak Jelang Ramadan 2026', '- Menurut media HARIAN DISWAY, pada 02 Jan 2026, Sepekan Cuaca Ekstrem di Jatim, Berlaku di 38 Kabupaten Kota', '- Menurut media Radar Tuban, pada 08 Jan 2026, Waspada Cuaca Ekstrem! Gelombang Laut di Sejumlah Perairan Indonesia Berpotensi Tembus 6 Meter', '- Menurut media Kompas.com, pada 05 Jan 2026, BMKG Prediksi Hujan Lebat dan Angin Kencang hingga 8 Januari 2026 akibat Siklon Tropis', '- Menurut media CNN Indonesia, pada 02 Jan 2026, Prediksi Cuaca Awal Tahun 2026', '- Menurut media RRI.co.id, pada 03 Jan 2026, BMKG Imbau Dampak Siklon Tropis IGGY', '- Menurut media Kompas.com, pada 08 Jan 2026, BMKG Beri Peringatan Dini Cuaca Ekstrem 8 Januari 2026: Daftar Wilayah Berpotensi Hujan Lebat', '- Menurut media Jawa Pos, pada 07 Jan 2026, Cuaca Ekstrem, KSOP Khusus Batam Keluarkan Peringatan Dini Keselamatan Pelayaran', '- Menurut media Liputan6.com, pada 05 Jan 2026, Terdampak Bencana, Aceh Alami Inflasi Tertinggi Nasional Tembus 3,60%', '- Menurut media Liputan6.com, pada 08 Jan 2026, Wamendagri Akhmad Wiyagus Apresiasi Penanganan Banjir Bandang Sitaro']
news
 ['- Menurut media Liputan6.com, pada 07 Jan 2026, Waspada Cuaca Ekstrem, Harga Pangan Berpotensi Melonjak Jelang Ramadan 2026', '- Menurut media HARIAN DISWAY, pada 02 Jan 2026, Sepekan Cuaca Ekstrem di Jatim, Berlaku di 38 Kabupaten Kota', '- Menurut media Radar Tuban, pada 08 Jan 2026, Waspada Cuaca Ekstrem! Gelombang Laut di Sejumlah Perairan Indonesia Berpotensi Tembus 6 Meter', '- Menurut media Kompas.com, pada 05 Jan 2026, BMKG Prediksi Hujan Lebat dan Angin Kencang hingga 8 Januari 2026 akibat Siklon Tropis', '- Menurut media CNN Indonesia, pada 02 Jan 2026, Prediksi Cuaca Awal Tahun 2026', '- Menurut media RRI.co.id, pada 03 Jan 2026, BMKG Imbau Dampak Siklon Tropis IGGY', '- Menurut media Kompas.com, pada 08 Jan 2026, BMKG Beri Peringatan Dini Cuaca Ekstrem 8 Januari 2026: Daftar Wilayah Berpotensi Hujan Lebat', '- Menurut media Jawa Pos, pada 07 Jan 2026, Cuaca Ekstrem, KSOP Khusus Batam Keluarkan Peringatan Dini Keselamatan Pelayaran', '- Menurut media Liputan6.com, pada 05 Jan 2026, Terdampak Bencana, Aceh Alami Inflasi Tertinggi Nasional Tembus 3,60%', '- Menurut media Liputan6.com, pada 08 Jan 2026, Wamendagri Akhmad Wiyagus Apresiasi Penanganan Banjir Bandang Sitaro']
 id 34 [35/44] 2026-01-12 → 2026-01-12 ...

/home/dimas/.local/lib/python3.10/site-packages/gnews/gnews.py:146: UserWarning: The start and end dates should be at least 1 day apart.
  warnings.warn("The start and end dates should be at least 1 day apart.")

total berita 3 | holiday 7
hari besar
 ['Berdekatan dengan hari besar:', "- Isra' and Mi'raj (estimated) (16-01-2026)", '', 'Terjadi peristiwa:', '- Menurut media beritajatim.com, pada 12 Jan 2026, Cuaca Ekstrem Mengintai Jawa Timur, Termasuk Bojonegoro', '- Menurut media ANTARA News Jateng, pada 12 Jan 2026, BMKG imbau waspadai cuaca ekstrem tiga hari ke depan di wilayah Pantura', '- Menurut media MetroTVNews.com, pada 12 Jan 2026, BMKG: Waspada Hujan Petir di Jaksel dan Jaktim Hari Ini']
news
 ['- Menurut media beritajatim.com, pada 12 Jan 2026, Cuaca Ekstrem Mengintai Jawa Timur, Termasuk Bojonegoro', '- Menurut media ANTARA News Jateng, pada 12 Jan 2026, BMKG imbau waspadai cuaca ekstrem tiga hari ke depan di wilayah Pantura', '- Menurut media MetroTVNews.com, pada 12 Jan 2026, BMKG: Waspada Hujan Petir di Jaksel dan Jaktim Hari Ini']
 id 35 [36/44] 2026-01-14 → 2026-01-14 ...

/home/dimas/.local/lib/python3.10/site-packages/gnews/gnews.py:146: UserWarning: The start and end dates should be at least 1 day apart.
  warnings.warn("The start and end dates should be at least 1 day apart.")

total berita 1 | holiday 5
hari besar
 ['Berdekatan dengan hari besar:', "- Isra' and Mi'raj (estimated) (16-01-2026)", '', 'Terjadi peristiwa:', '- Menurut media Suara Ternate, pada 14 Jan 2026, Potensi Cuaca Ekstrim, Gubernur Sherly Minta Masyarakat Waspada dan Tunda Perjalanan']
news
 ['- Menurut media Suara Ternate, pada 14 Jan 2026, Potensi Cuaca Ekstrim, Gubernur Sherly Minta Masyarakat Waspada dan Tunda Perjalanan']
 id 36 [37/44] 2026-01-23 → 2026-01-25 ... total berita 9 | holiday 13
hari besar
 ['Berdekatan dengan hari besar:', "- Isra' and Mi'raj (estimated) (16-01-2026)", '', 'Terjadi peristiwa:', '- Menurut media Tugu Malang ID, pada 24 Jan 2026, Cuaca Ekstrem Akan Melanda Malang hingga Akhir Januari 2026', '- Menurut media SinPo.id, pada 25 Jan 2026, BMKG Peringatkan Cuaca Ekstrem Akhir Pekan di Jakarta dan Sejumlah Wilayah', '- Menurut media Kompas.tv, pada 23 Jan 2026, Indonesia Masih Berpotensi Dihantam Cuaca Ekstrem hingga 29 Januari 2026, BMKG Ungkap Penyebabnya', '- Menurut media HARIAN MISTAR, pada 23 Jan 2026, BMKG: Cuaca Ekstrem Belum Berakhir, Hujan Lebat Ancam Indonesia hingga 29 Januari', '- Menurut media NU Online Jakarta, pada 23 Jan 2026, Dinas Pendidikan Jakarta Terapkan PJJ karena Cuaca Ekstrem', '- Menurut media ANTARA News, pada 23 Jan 2026, Waspadai hujan lebat hingga ekstrem di sebagian besar RI pada Jumat', '- Menurut media Liputan6.com, pada 23 Jan 2026, Longsor di Manggarai Timur NTT, 1 Orang Tewas dan 2 Hilang Tertimbun', '- Menurut media BeritaSatu.com, pada 23 Jan 2026, Cuaca Ekstrem, Pemprov Jakarta Imbau Perusahaan Terapkan WFH', '- Menurut media ANTARA News, pada 24 Jan 2026, BMKG beber penyebab angin kencang yang melanda wilayah Malang']
news
 ['- Menurut media Tugu Malang ID, pada 24 Jan 2026, Cuaca Ekstrem Akan Melanda Malang hingga Akhir Januari 2026', '- Menurut media SinPo.id, pada 25 Jan 2026, BMKG Peringatkan Cuaca Ekstrem Akhir Pekan di Jakarta dan Sejumlah Wilayah', '- Menurut media Kompas.tv, pada 23 Jan 2026, Indonesia Masih Berpotensi Dihantam Cuaca Ekstrem hingga 29 Januari 2026, BMKG Ungkap Penyebabnya', '- Menurut media HARIAN MISTAR, pada 23 Jan 2026, BMKG: Cuaca Ekstrem Belum Berakhir, Hujan Lebat Ancam Indonesia hingga 29 Januari', '- Menurut media NU Online Jakarta, pada 23 Jan 2026, Dinas Pendidikan Jakarta Terapkan PJJ karena Cuaca Ekstrem', '- Menurut media ANTARA News, pada 23 Jan 2026, Waspadai hujan lebat hingga ekstrem di sebagian besar RI pada Jumat', '- Menurut media Liputan6.com, pada 23 Jan 2026, Longsor di Manggarai Timur NTT, 1 Orang Tewas dan 2 Hilang Tertimbun', '- Menurut media BeritaSatu.com, pada 23 Jan 2026, Cuaca Ekstrem, Pemprov Jakarta Imbau Perusahaan Terapkan WFH', '- Menurut media ANTARA News, pada 24 Jan 2026, BMKG beber penyebab angin kencang yang melanda wilayah Malang']
 id 37 [38/44] 2026-01-27 → 2026-01-27 ...

/home/dimas/.local/lib/python3.10/site-packages/gnews/gnews.py:146: UserWarning: The start and end dates should be at least 1 day apart.
  warnings.warn("The start and end dates should be at least 1 day apart.")

total berita 3 | holiday 4
hari besar
 ['Terjadi peristiwa:', '- Menurut media Kompas.com, pada 27 Jan 2026, Waspada, Cuaca Ekstrem Masih Membayangi Wilayah Indonesia', '- Menurut media beritabuana.co, pada 27 Jan 2026, Waspada dan Siaga! BMKG Ingatkan Potensi Cuaca Ekstrem Picu Banjir Bandang dan Longsor', '- Menurut media Kompas.tv, pada 27 Jan 2026, Peringatan Dini BMKG 28-29 Januari 2026: Hujan Lebat Mengintai, Sejumlah Wilayah Siaga']
news
 ['- Menurut media Kompas.com, pada 27 Jan 2026, Waspada, Cuaca Ekstrem Masih Membayangi Wilayah Indonesia', '- Menurut media beritabuana.co, pada 27 Jan 2026, Waspada dan Siaga! BMKG Ingatkan Potensi Cuaca Ekstrem Picu Banjir Bandang dan Longsor', '- Menurut media Kompas.tv, pada 27 Jan 2026, Peringatan Dini BMKG 28-29 Januari 2026: Hujan Lebat Mengintai, Sejumlah Wilayah Siaga']
 id 38 [39/44] 2026-01-29 → 2026-01-30 ... total berita 4 | holiday 5
hari besar
 ['Terjadi peristiwa:', '- Menurut media Tribun Video, pada 29 Jan 2026, Waspada Cuaca Ekstrem, BMKG Ini Wilayah yang Akan Hujan Lebat pada Kamis 30 Januari 2026', '- Menurut media Kompas.com, pada 29 Jan 2026, Cuaca Ekstrem di Indonesia Diprediksi hingga Maret 2026, Ini Kata BMKG', '- Menurut media tvOneNews, pada 29 Jan 2026, Jawa Barat Status Awas, BMKG Rilis Peringatan Dini Cuaca Ekstrem 27-29 Januari 2026', '- Menurut media RRI.co.id, pada 29 Jan 2026, BPBD Talaud Imbau Masyarakat Waspada Guaca Ekstrim']
news
 ['- Menurut media Tribun Video, pada 29 Jan 2026, Waspada Cuaca Ekstrem, BMKG Ini Wilayah yang Akan Hujan Lebat pada Kamis 30 Januari 2026', '- Menurut media Kompas.com, pada 29 Jan 2026, Cuaca Ekstrem di Indonesia Diprediksi hingga Maret 2026, Ini Kata BMKG', '- Menurut media tvOneNews, pada 29 Jan 2026, Jawa Barat Status Awas, BMKG Rilis Peringatan Dini Cuaca Ekstrem 27-29 Januari 2026', '- Menurut media RRI.co.id, pada 29 Jan 2026, BPBD Talaud Imbau Masyarakat Waspada Guaca Ekstrim']
 id 39 [40/44] 2026-02-02 → 2026-02-02 ...

/home/dimas/.local/lib/python3.10/site-packages/gnews/gnews.py:146: UserWarning: The start and end dates should be at least 1 day apart.
  warnings.warn("The start and end dates should be at least 1 day apart.")

total berita 1 | holiday 2
hari besar
 ['Terjadi peristiwa:', '- Menurut media ANTARA News Megapolitan, pada 02 Feb 2026, 19 rumah warga rusak akibat hujan dan angin kencang di Makassar']
news
 ['- Menurut media ANTARA News Megapolitan, pada 02 Feb 2026, 19 rumah warga rusak akibat hujan dan angin kencang di Makassar']
 id 40 [41/44] 2026-02-04 → 2026-02-04 ...

/home/dimas/.local/lib/python3.10/site-packages/gnews/gnews.py:146: UserWarning: The start and end dates should be at least 1 day apart.
  warnings.warn("The start and end dates should be at least 1 day apart.")

total berita 0 | holiday 0
hari besar
 []
news
 []
 id 41 [42/44] 2026-02-06 → 2026-02-06 ...

/home/dimas/.local/lib/python3.10/site-packages/gnews/gnews.py:146: UserWarning: The start and end dates should be at least 1 day apart.
  warnings.warn("The start and end dates should be at least 1 day apart.")

total berita 3 | holiday 4
hari besar
 ['Terjadi peristiwa:', '- Menurut media CNN Indonesia, pada 06 Feb 2026, Peringatan BMKG: Cuaca Ekstrem Mengintai Indonesia Sepekan ke Depan', '- Menurut media CNN Indonesia, pada 06 Feb 2026, Dampak Krisis Iklim, Hujan di Indonesia Makin Ekstrem', '- Menurut media Siaga Indonesia, pada 06 Feb 2026, Wali Kota Eri Imbau Warga Siaga Hadapi Cuaca Ekstrim, Komisi A: CC Room dan Call Centre 112 Harus Standby 24 Jam']
news
 ['- Menurut media CNN Indonesia, pada 06 Feb 2026, Peringatan BMKG: Cuaca Ekstrem Mengintai Indonesia Sepekan ke Depan', '- Menurut media CNN Indonesia, pada 06 Feb 2026, Dampak Krisis Iklim, Hujan di Indonesia Makin Ekstrem', '- Menurut media Siaga Indonesia, pada 06 Feb 2026, Wali Kota Eri Imbau Warga Siaga Hadapi Cuaca Ekstrim, Komisi A: CC Room dan Call Centre 112 Harus Standby 24 Jam']
 id 42 [43/44] 2026-02-14 → 2026-02-14 ...

/home/dimas/.local/lib/python3.10/site-packages/gnews/gnews.py:146: UserWarning: The start and end dates should be at least 1 day apart.
  warnings.warn("The start and end dates should be at least 1 day apart.")

total berita 0 | holiday 2
hari besar
 ['Berdekatan dengan hari besar:', '- Lunar New Year (estimated) (17-02-2026)']
news
 []
 id 43 [44/44] 2026-02-16 → 2026-02-26 ... total berita 11 | holiday 15
hari besar
 ['Berdekatan dengan hari besar:', '- Lunar New Year (estimated) (17-02-2026)', '', 'Terjadi peristiwa:', '- Menurut media Nusadaily, pada 23 Feb 2026, Awas! BMKG Peringatkan Malang Raya dan Jatim Waspada Cuaca Ekstrem', '- Menurut media Sinergia Mediatama, pada 19 Feb 2026, Waspada Cuaca Ekstrem di Madiun, Sejumlah Rumah Rusak Diterjang Hujan dan Angin Kencang', '- Menurut media RRI.co.id, pada 16 Feb 2026, Cuaca Ekstrim Harga Cabai Melonjak Rp 45.000/Kg', '- Menurut media Beritajateng.tv, pada 24 Feb 2026, Kamis Berpotensi Diguyur Hujan Lebat, BMKG Imbau Masyarakat Tingkatkan Kewaspadaan', '- Menurut media VIVA Banyuwangi, pada 23 Feb 2026, Cuaca Ekstrem, KAI Daop 9 Jember Perkuat Infrastruktur dan Siagakan Petugas Ekstra', '- Menurut media Beritajateng.tv, pada 22 Feb 2026, Cuaca Minggu 22 Februari 2026: Waspada Hujan Lebat dan Petir di Sejumlah Wilayah', '- Menurut media Beritajateng.tv, pada 22 Feb 2026, Waspada Cuaca Ekstrem! Ini Prakiraan Lengkap BMKG untuk Senin, 23 Februari 2026', '- Menurut media Beritajateng.tv, pada 20 Feb 2026, Cuaca Jumat, 20 Februari 2026: BMKG Peringatkan Potensi Hujan Lebat di Sejumlah Wilayah', '- Menurut media Beritajateng.tv, pada 19 Feb 2026, Prakiraan Cuaca 19 Februari 2026 : Waspada Cuaca Ekstrem Jawa Tengah di Wilayah Muria', '- Menurut media Beritajateng.tv, pada 24 Feb 2026, Waspada Hujan Lebat, BMKG Rilis Prakiraan Cuaca Rabu 25 Februari 2026', '- Menurut media Beritajateng.tv, pada 24 Feb 2026, Cuaca Indonesia 24 Februari 2026: Sejumlah Wilayah Berpotensi Hujan Lebat hingga Petir']
news
 ['- Menurut media Nusadaily, pada 23 Feb 2026, Awas! BMKG Peringatkan Malang Raya dan Jatim Waspada Cuaca Ekstrem', '- Menurut media Sinergia Mediatama, pada 19 Feb 2026, Waspada Cuaca Ekstrem di Madiun, Sejumlah Rumah Rusak Diterjang Hujan dan Angin Kencang', '- Menurut media RRI.co.id, pada 16 Feb 2026, Cuaca Ekstrim Harga Cabai Melonjak Rp 45.000/Kg', '- Menurut media Beritajateng.tv, pada 24 Feb 2026, Kamis Berpotensi Diguyur Hujan Lebat, BMKG Imbau Masyarakat Tingkatkan Kewaspadaan', '- Menurut media VIVA Banyuwangi, pada 23 Feb 2026, Cuaca Ekstrem, KAI Daop 9 Jember Perkuat Infrastruktur dan Siagakan Petugas Ekstra', '- Menurut media Beritajateng.tv, pada 22 Feb 2026, Cuaca Minggu 22 Februari 2026: Waspada Hujan Lebat dan Petir di Sejumlah Wilayah', '- Menurut media Beritajateng.tv, pada 22 Feb 2026, Waspada Cuaca Ekstrem! Ini Prakiraan Lengkap BMKG untuk Senin, 23 Februari 2026', '- Menurut media Beritajateng.tv, pada 20 Feb 2026, Cuaca Jumat, 20 Februari 2026: BMKG Peringatkan Potensi Hujan Lebat di Sejumlah Wilayah', '- Menurut media Beritajateng.tv, pada 19 Feb 2026, Prakiraan Cuaca 19 Februari 2026 : Waspada Cuaca Ekstrem Jawa Tengah di Wilayah Muria', '- Menurut media Beritajateng.tv, pada 24 Feb 2026, Waspada Hujan Lebat, BMKG Rilis Prakiraan Cuaca Rabu 25 Februari 2026', '- Menurut media Beritajateng.tv, pada 24 Feb 2026, Cuaca Indonesia 24 Februari 2026: Sejumlah Wilayah Berpotensi Hujan Lebat hingga Petir']

## Setup Coloumn

In [69]:
outlier_detail['id_harga_beras'] = outlier_detail['id']
outlier_detail['id'] = outlier_detail['row_id']+last_id_detail
outlier_detail['id_group'] = outlier_detail['cluster_id']+last_id_group
outlier_detail = outlier_detail[['id', 'id_harga_beras', 'id_group']]

# Menghapus duplikat berdasarkan kolom 'id_harga_beras' dan 'id_group', hanya menyisakan satu baris
outlier_detail = outlier_detail.drop_duplicates(subset=['id_harga_beras', 'id_group'], keep='first')

# Menampilkan hasil
print(f"Jumlah baris setelah duplikat dihapus: {outlier_detail.shape[0]}")
outlier_detail[outlier_detail['id_group'] == last_id_group+1]

Jumlah baris setelah duplikat dihapus: 1322

        id  id_harga_beras  id_group
418  13600          206097       540
419  13601          206098       540
420  13602          206099       540
421  13603          206100       540
422  13604          206101       540
..     ...             ...       ...
868  14050          243565       540
869  14051          243566       540
870  14052          243567       540
871  14053          243568       540
872  14054          243569       540

[110 rows x 3 columns]

In [70]:
outlier_group['id'] = outlier_group['cluster_id']+last_id_group
outlier_group = outlier_group[['id', 'deskripsi']]
outlier_group

     id                                          deskripsi
0   540  Terjadi peristiwa:\n- Menurut media CNN Indone...
1   541  Berdekatan dengan hari besar:\n- Lunar New Yea...
2   542  Berdekatan dengan hari besar:\n- Lunar New Yea...
3   543  Berdekatan dengan hari besar:\n- Lunar New Yea...
4   544  Berdekatan dengan hari besar:\n- New Year's Da...
5   545  Berdekatan dengan hari besar:\n- Isra' and Mi'...
6   546  Tidak ditemukan peristiwa dalam periode tersebut.
7   547  Terjadi peristiwa:\n- Menurut media Kompas.tv,...
8   548  Berdekatan dengan hari besar:\n- Lunar New Yea...
9   549  Berdekatan dengan hari besar:\n- Lunar New Yea...
10  550  Berdekatan dengan hari besar:\n- Lunar New Yea...
11  551  Berdekatan dengan hari besar:\n- New Year's Da...
12  552  Berdekatan dengan hari besar:\n- Isra' and Mi'...
13  553  Terjadi peristiwa:\n- Menurut media SinPo.id, ...
14  554  Terjadi peristiwa:\n- Menurut media ANTARA New...
15  555  Terjadi peristiwa:\n- Menurut media Kompas.tv,...
16  556  Berdekatan dengan hari besar:\n- Lunar New Yea...
17  557  Berdekatan dengan hari besar:\n- Lunar New Yea...
18  558  Berdekatan dengan hari besar:\n- Lunar New Yea...
19  559  Berdekatan dengan hari besar:\n- New Year's Da...
20  560  Berdekatan dengan hari besar:\n- Isra' and Mi'...
21  561  Terjadi peristiwa:\n- Menurut media Qoo10.co.i...
22  562  Berdekatan dengan hari besar:\n- Lunar New Yea...
23  563  Berdekatan dengan hari besar:\n- Lunar New Yea...
24  564  Berdekatan dengan hari besar:\n- Lunar New Yea...
25  565  Berdekatan dengan hari besar:\n- Lunar New Yea...
26  566  Berdekatan dengan hari besar:\n- Lunar New Yea...
27  567  Berdekatan dengan hari besar:\n- New Year's Da...
28  568  Berdekatan dengan hari besar:\n- Isra' and Mi'...
29  569  Terjadi peristiwa:\n- Menurut media Kompas.com...
30  570  Terjadi peristiwa:\n- Menurut media CNN Indone...
31  571  Berdekatan dengan hari besar:\n- Lunar New Yea...
32  572  Berdekatan dengan hari besar:\n- Lunar New Yea...
33  573  Berdekatan dengan hari besar:\n- New Year's Da...
34  574  Berdekatan dengan hari besar:\n- Isra' and Mi'...
35  575  Berdekatan dengan hari besar:\n- Isra' and Mi'...
36  576  Berdekatan dengan hari besar:\n- Isra' and Mi'...
37  577  Terjadi peristiwa:\n- Menurut media Kompas.com...
38  578  Terjadi peristiwa:\n- Menurut media Tribun Vid...
39  579  Terjadi peristiwa:\n- Menurut media ANTARA New...
40  580  Tidak ditemukan peristiwa dalam periode tersebut.
41  581  Terjadi peristiwa:\n- Menurut media CNN Indone...
42  582  Berdekatan dengan hari besar:\n- Lunar New Yea...
43  583  Berdekatan dengan hari besar:\n- Lunar New Yea...

## Insert Into Supabase

In [71]:
import math

def insert_large_data(table_name, data, batch_size=900):
    total = len(data)
    batches = math.ceil(total / batch_size)

    for i in range(batches):
        start = i * batch_size
        end = start + batch_size
        batch = data[start:end]

        response = supabase.table(table_name).insert(batch).execute()

        if response.data is None:
            print("Error:", response)
            break

        print(f"Batch {i+1}/{batches} berhasil ({len(batch)} rows)")

    print("Selesai insert.")

# ======================
# CONTOH PAKAI
# ======================
outlier_group_list = outlier_group.to_dict(orient="records")

insert_large_data("outlier_group", outlier_group_list)

03/03/2026 01:59:00 PM - HTTP Request: POST https://extlxiwpcbzqaalpopqn.supabase.co/rest/v1/outlier_group?columns=%22deskripsi%22%2C%22id%22 "HTTP/2 201 Created"

Batch 1/1 berhasil (44 rows)
Selesai insert.

In [72]:
outlier_detail_list = outlier_detail.to_dict(orient="records")

insert_large_data("outlier_detail", outlier_detail_list)

03/03/2026 01:59:01 PM - HTTP Request: POST https://extlxiwpcbzqaalpopqn.supabase.co/rest/v1/outlier_detail?columns=%22id_harga_beras%22%2C%22id_group%22%2C%22id%22 "HTTP/2 201 Created"
03/03/2026 01:59:01 PM - HTTP Request: POST https://extlxiwpcbzqaalpopqn.supabase.co/rest/v1/outlier_detail?columns=%22id_harga_beras%22%2C%22id_group%22%2C%22id%22 "HTTP/2 201 Created"

Batch 1/2 berhasil (900 rows)
Batch 2/2 berhasil (422 rows)
Selesai insert.